import {prisma} from '@/lib/prisma';
import {getAccountForRequest} from '@/lib/auth/userService';
export const runtime='nodejs';export const dynamic='force-dynamic';
const ok=(data:unknown,status=200)=>Response.json({data,error:null},{status,headers:{'Cache-Control':'no-store'}}),fail=(message:string,status=400)=>Response.json({data:null,error:{message}},{status});
const json=(r:Request)=>r.json().catch(()=>({})) as Promise<Record<string,unknown>>,str=(v:unknown,n=500)=>typeof v==='string'&&v.trim()?v.trim().slice(0,n):null;
const profiles=(prisma as unknown as {watchlistNotificationProfile:any}).watchlistNotificationProfile;
async function owner(r:Request){const user=await getAccountForRequest(r);if(!user)throw Error('AUTH');return user}
export async function GET(r:Request){try{const user=await owner(r);return ok(await profiles.findMany({where:{userId:user.id,channelType:'APP_PUSH'},select:{id:true,enabled:true,timezone:true,quietHours:true,frequencyCap:true,updatedAt:true},orderBy:{updatedAt:'desc'}}))}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to load push preferences.',e instanceof Error&&e.message==='AUTH'?401:500)}}
export async function POST(r:Request){try{const user=await owner(r),b=await json(r),token=str(b.token),timezone=str(b.timezone,80)??'UTC';if(!token||!/^ExponentPushToken\[[^\]]+\]$|^ExpoPushToken\[[^\]]+\]$/.test(token))return fail('Invalid Expo push token.');if(b.previousToken&&b.previousToken!==token)await profiles.updateMany({where:{userId:user.id,channelType:'APP_PUSH',destinationReference:String(b.previousToken)},data:{enabled:false}});const existing=await profiles.findFirst({where:{userId:user.id,channelType:'APP_PUSH',destinationReference:token}});const data={enabled:true,timezone,quietHours:b.quietHours??undefined,frequencyCap:b.frequencyCap??{maxPerDay:null,entitlementControlled:true},criticalBypassPolicy:'USER_ALERTS_ONLY'};const row=existing?await profiles.update({where:{id:existing.id},data}):await profiles.create({data:{userId:user.id,channelType:'APP_PUSH',destinationReference:token,...data,isTest:false}});return ok({id:row.id,enabled:row.enabled,timezone:row.timezone,frequencyCap:row.frequencyCap},existing?200:201)}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to register device.',e instanceof Error&&e.message==='AUTH'?401:500)}}
export async function PATCH(r:Request){try{const user=await owner(r),b=await json(r),id=str(b.id);if(!id)return fail('Device is required.');const row=await profiles.findFirst({where:{id,userId:user.id,channelType:'APP_PUSH'}});if(!row)return fail('Device not found.',404);return ok(await profiles.update({where:{id},data:{...(typeof b.enabled==='boolean'?{enabled:b.enabled}:{}),...(b.quietHours!==undefined?{quietHours:b.quietHours as object}:{}),...(b.frequencyCap!==undefined?{frequencyCap:b.frequencyCap as object}:{})},select:{id:true,enabled:true,timezone:true,quietHours:true,frequencyCap:true}}))}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to update push preferences.',e instanceof Error&&e.message==='AUTH'?401:500)}}
export async function DELETE(r:Request){try{const user=await owner(r),b=await json(r),token=str(b.token);if(!token)return fail('Token is required.');await profiles.updateMany({where:{userId:user.id,channelType:'APP_PUSH',destinationReference:token},data:{enabled:false}});return ok({removed:true})}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to remove device.',e instanceof Error&&e.message==='AUTH'?401:500)}}
