"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { HomeMarketCard, HomeMarketOverview, HomeMarketTab } from "@/lib/data-platform/web/homeMarketService";

const TABS:Array<{key:HomeMarketTab;label:string}>=[{key:"stocks",label:"股票指數"},{key:"bonds",label:"債券與利率"},{key:"fx",label:"外匯"},{key:"commodities",label:"商品"},{key:"crypto",label:"加密資產"}];
const links=[["股票","/search?type=STOCK"],["ETF","/etf"],["基金","/fund"],["固定收益","/search?type=FIXED_INCOME"],["指數","/search?type=INDEX"],["衍生品","/search?type=DERIVATIVES"],["外匯","/search?type=FX"],["總經","/search?type=MACRO"],["商品","/search?type=COMMODITY"],["加密資產","/search?type=CRYPTO"]] as const;
const names:Record<string,string>={"^GSPC":"標普 500 指數","^IXIC":"那斯達克綜合指數","^N225":"日經 225 指數","^TWII":"台灣加權指數","VIX":"CBOE 波動率指數","USDTWD=X":"美元／新台幣","EURUSD=X":"歐元／美元","JPY=X":"美元／日圓"};
const status=(v:string)=>({CURRENT:"最新",STALE:"資料延遲",HEALTHY_WAITING:"正常等待",SOURCE_WAIT:"等待資料發布",UNKNOWN:"狀態待確認"}[v]??"狀態待確認");
const keyOf=(r:HomeMarketCard)=>`${r.assetType}:${r.id}`;
export default function MarketsPage(){
 const [data,setData]=useState<HomeMarketOverview|null>(null),[tab,setTab]=useState<HomeMarketTab>("stocks"),[manage,setManage]=useState(false),[order,setOrder]=useState<Partial<Record<HomeMarketTab,string[]>>>({});
 useEffect(()=>{fetch("/api/home-market-overview",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json()}).then((v:HomeMarketOverview)=>{setData(v);const saved=localStorage.getItem("smartmatch-market-cards");if(saved)setOrder(JSON.parse(saved))}).catch(()=>undefined)},[]);
 const available=data?.available?.[tab]??data?.tabs[tab]??[];
 const selected=order[tab]??(data?.tabs[tab]??[]).map(keyOf);
 const rows=useMemo(()=>selected.map(id=>available.find(r=>keyOf(r)===id)).filter((r):r is HomeMarketCard=>Boolean(r)),[available,selected]);
 const save=(next:string[])=>{const value={...order,[tab]:next};setOrder(value);localStorage.setItem("smartmatch-market-cards",JSON.stringify(value))};
 const toggle=(id:string)=>save(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
 const move=(id:string,step:number)=>{const next=[...selected],i=next.indexOf(id),j=i+step;if(i<0||j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];save(next)};
 return <main className="min-h-screen bg-gradient-to-b from-[#07111f] via-[#0b1728] to-[#040a18] text-white">
  <header className="border-b border-white/10 bg-[#040a18]/95"><div className="mx-auto flex min-h-20 max-w-[1500px] flex-wrap items-center justify-between gap-4 px-6 py-4 md:px-10"><Link href="/" className="text-[28px] font-black">Smart<span className="text-[#F5B700]">Match</span></Link><nav className="flex flex-wrap items-center gap-3 text-[14px] text-slate-300"><Link href="/markets" className="text-[#F5B700]">市場總覽</Link>{links.map(([label,href])=><Link key={label} href={href} className="rounded-md px-2 py-1 hover:bg-white/[0.07] hover:text-white">{label}</Link>)}</nav></div></header>
  <section className="mx-auto max-w-[1500px] px-6 py-12 md:px-10"><div className="text-[14px] font-bold tracking-[.2em] text-[#F5B700]">SmartMatch 市場資料</div><h1 className="mt-4 text-4xl font-black md:text-5xl">全球市場總覽</h1><p className="mt-3 text-[16px] text-slate-300">只呈現目前有正式資料的市場項目，可自行新增、移除及排序。</p>
   <div className="mt-8 flex flex-wrap items-center gap-2">{TABS.map(x=><button key={x.key} onClick={()=>{setTab(x.key);setManage(false)}} className={`rounded-xl px-4 py-2 text-[14px] font-bold ${tab===x.key?"bg-[#F5B700] text-[#07111f]":"border border-white/15 bg-white/[0.04] text-slate-300"}`}>{x.label}</button>)}<button onClick={()=>setManage(v=>!v)} className="ml-auto rounded-xl border border-[#F5B700]/40 px-4 py-2 text-[14px] font-bold text-[#F5B700]">管理顯示</button></div>
   {tab==="stocks"&&data&&<p className="mt-3 text-[14px] text-slate-400">指數資料庫共 {data.indexRegistryCount.toLocaleString("zh-TW")} 項；主畫面只顯示你選擇且已有正式數值的項目。</p>}
   {manage&&<div className="mt-4 rounded-2xl border border-white/10 bg-[#091526] p-4"><h2 className="text-[24px] font-black">管理顯示項目</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{available.map(r=>{const id=keyOf(r),on=selected.includes(id);return <div key={id} className="flex items-center gap-2 rounded-lg border border-white/10 p-3"><label className="flex min-w-0 flex-1 items-center gap-2 text-[15px]"><input type="checkbox" checked={on} onChange={()=>toggle(id)}/><span className="truncate">{names[r.symbolOrCode??""]??r.label} <span className="text-slate-500">{r.symbolOrCode}</span></span></label>{on&&<><button aria-label="上移" onClick={()=>move(id,-1)} className="px-2">↑</button><button aria-label="下移" onClick={()=>move(id,1)} className="px-2">↓</button></>}</div>})}</div></div>}
   <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{rows.map(r=><Card key={keyOf(r)} row={r}/>)}</div>
   <div className="mt-5 text-[14px] text-slate-400">資料產生時間：{data?new Date(data.generatedAt).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}):"—"}</div>
  </section>
 </main>
}
function Card({row}:{row:HomeMarketCard}){const label=names[row.symbolOrCode??""]??row.label;const v=row.value==null?"—":row.value.toLocaleString("zh-TW",{maximumFractionDigits:4});const content=<><div className="flex justify-between gap-2"><div><h2 className="text-[18px] font-black">{label}</h2><p className="mt-1 font-mono text-[14px] text-[#F5B700]">{row.symbolOrCode}</p></div><span className="h-fit rounded-full bg-white/[0.07] px-2 py-1 text-[12px]">{status(row.freshnessStatus)}</span></div><div className="mt-6 text-3xl font-black">{v}{row.unit?` ${row.unit}`:row.currency?` ${row.currency}`:""}</div><div className={`mt-2 text-[15px] ${(row.changePercent??0)>=0?"text-emerald-300":"text-rose-300"}`}>{row.changePercent==null?"變動資料未提供":`${row.changePercent>0?"+":""}${row.changePercent.toFixed(2)}%`}</div><div className="mt-5 border-t border-white/10 pt-3 text-[14px] text-slate-400">資料日期：{row.asOfDate?.slice(0,10)??"—"}</div></>;const cls="rounded-2xl border border-white/10 bg-white/[0.06] p-5";return row.detailHref?<Link href={row.detailHref} className={`${cls} transition hover:border-[#F5B700]/40`}>{content}</Link>:<article className={cls}>{content}</article>}