import Link from "next/link";

import { globalSearch, SEARCH_ASSET_TYPES, type GlobalSearchResponse, type SearchType, type UnifiedSearchResult } from "@/lib/data-platform/web/searchService";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const validType = (value: string | undefined): SearchType => value && SEARCH_ASSET_TYPES.includes(value as (typeof SEARCH_ASSET_TYPES)[number]) ? value as SearchType : "ALL";
const numberLabel = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("zh-TW", { maximumFractionDigits: 6 }).format(value);
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("zh-TW", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)) : "—";
const display = (value: string | null | undefined, fallback = "資料未提供") => value?.trim() || fallback;
const typeLabels: Record<SearchType, string> = { ALL: "全部", STOCK: "股票", ETF: "ETF", FUND: "基金", INDEX: "指數", DERIVATIVES: "衍生品", FIXED_INCOME: "固定收益", FX: "外匯", MACRO: "總經", COMMODITY: "商品", CRYPTO: "加密資產" };

export default async function SearchPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const query = first(params.q)?.trim() ?? "";
  const type = validType(first(params.type)?.toUpperCase());
  let response: GlobalSearchResponse | null = null;
  let error: "INVALID_QUERY" | "DATA_UNAVAILABLE" | "INTERNAL_ERROR" | null = null;
  if (query) {
    try { response = await globalSearch({ query, type: "ALL" }); }
    catch (caught) { error = caught instanceof Error && caught.message.includes("between 1 and 100") ? "INVALID_QUERY" : "DATA_UNAVAILABLE"; }
  }
  const allRows = response?.data ?? [];
  const normalizedQuery = query.normalize("NFKC").trim().toLowerCase();
  const exactAcrossTypes = allRows.filter((row) => (row.symbolOrCode ?? "").normalize("NFKC").trim().toLowerCase() === normalizedQuery);
  const rows = type === "ALL" ? allRows : [...exactAcrossTypes, ...allRows.filter((row) => row.assetType === type && !exactAcrossTypes.includes(row))];
  const crossTypeExact = type !== "ALL" ? exactAcrossTypes.find((row) => row.assetType !== type) : undefined;

  return <main className="min-h-screen bg-[#07111f] text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[0.08] bg-[#040a18]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1600px] items-center justify-between px-4 sm:px-10"><Link href="/"><div className="text-[28px] font-black leading-none sm:text-[32px]">Smart<span className="text-[#F5B700]">Match</span></div><div className="mt-1 text-[10px] text-slate-500">全球投資研究平台</div></Link><nav className="hidden gap-7 text-sm font-semibold text-slate-300 lg:flex"><Link href="/markets" className="hover:text-white">市場總覽</Link><Link href="/etf" className="hover:text-white">ETF</Link><Link href="/funds" className="hover:text-white">基金</Link><Link href="/rankings" className="hover:text-white">排行榜</Link><Link href="/portfolio" className="hover:text-white">投資組合</Link></nav><Link href="/pricing" className="rounded-lg border border-white/20 px-4 py-2 text-sm text-slate-300">會員方案</Link></div></header>
    <div className="mx-auto max-w-[1450px] px-4 pb-20 pt-32 sm:px-8 md:px-10">
      <section className="mx-auto max-w-4xl text-center"><div className="text-xs font-semibold tracking-[0.3em] text-[#F5B700]">全球投資搜尋</div><h1 className="mt-4 text-[38px] font-black tracking-[-0.03em] md:text-[52px]">全球投資搜尋</h1><p className="mt-4 text-base leading-8 text-slate-400">一次搜尋全球股票、ETF、基金、指數與外匯市場。</p><form action="/search" role="search" className="mt-9"><input type="hidden" name="type" value={type} /><div className="flex h-[68px] items-center rounded-2xl border border-white/[0.16] bg-white/[0.97] px-4 shadow-[0_22px_70px_rgba(0,0,0,0.24)] focus-within:border-[#F5B700]/70 sm:px-6"><span className="mr-3 text-xl text-slate-500">⌕</span><input name="q" type="search" defaultValue={query} placeholder="搜尋名稱、代碼、Ticker、ISIN 或貨幣對" className="min-w-0 flex-1 bg-transparent text-[15px] font-medium text-slate-900 outline-none placeholder:text-slate-500 sm:text-base" /><button className="rounded-xl bg-[#0B1B34] px-5 py-3 text-sm font-bold text-white sm:px-7">搜尋</button></div></form><div className="mt-5 text-xs text-slate-500">快速搜尋支援名稱、代碼、Ticker、ISIN 與貨幣對；不顯示未經事件資料驗證的熱門排行。</div></section>
      <section className="mt-12 overflow-hidden rounded-2xl border border-white/[0.09] bg-white/[0.03]"><nav className="overflow-x-auto border-b border-white/[0.08] px-5"><div className="flex min-w-max gap-2 py-4">{(["ALL", ...SEARCH_ASSET_TYPES] as SearchType[]).map((item) => <Link key={item} href={`/search${query ? `?q=${encodeURIComponent(query)}&type=${item}` : `?type=${item}`}`} className={`rounded-lg px-5 py-2.5 text-[13px] font-bold ${type === item ? "bg-white/[0.1] text-white" : "text-slate-500 hover:text-slate-300"}`}>{typeLabels[item]}</Link>)}</div></nav>
        {crossTypeExact && <div className="border-b border-[#F5B700]/20 bg-[#F5B700]/[0.06] px-5 py-3 text-[14px] text-[#ffe18a]">{crossTypeExact.symbolOrCode} 是{typeLabels[crossTypeExact.assetType]}，已保留正確商品供你加入。</div>}
        {response?.meta.partial && <div className="border-b border-amber-500/15 bg-amber-500/[0.05] px-5 py-3 text-xs text-amber-300">部分資料來源暫時無法搜尋；目前顯示其餘 資產類別 的結果。未完成：{response.meta.failedDomains.join("、")}</div>}
        {!query ? <State title="輸入關鍵字開始搜尋" description="搜尋會在伺服器端查詢目前可用的資產類別。" /> : error ? <State title={error === "INVALID_QUERY" ? "搜尋條件無效" : "搜尋服務暫時無法使用"} description="請調整關鍵字或稍後再試；系統不會改用靜態結果。" /> : rows.length === 0 ? <State title="找不到符合條件的商品" description={`正式資料庫中沒有「${query}」的搜尋結果。`} /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left text-[15px]"><thead className="border-b border-white/[0.08] text-[14px] text-slate-400"><tr><th className="px-5 py-4">名稱</th><th className="px-5 py-4">代碼</th><th className="px-5 py-4">類型</th><th className="px-5 py-4">市場</th><th className="px-5 py-4">幣別</th><th className="px-5 py-4 text-right">最新值</th><th className="px-5 py-4">資料日期</th></tr></thead><tbody>{rows.map((row) => <ResultRow key={`${row.assetType}:${row.canonicalId}`} row={row} />)}</tbody></table></div><div className="divide-y divide-white/[0.07] md:hidden">{rows.map((row) => <ResultCard key={`${row.assetType}:${row.canonicalId}`} row={row} />)}</div></>}
      </section>
      {response && <div className="mt-4 flex flex-wrap justify-between gap-2 text-[11px] text-slate-600"><span>{response.meta.resultCount} 筆 · 搜尋範圍：{response.meta.typesSearched.join(" / ")}</span><span>產生時間：{dateLabel(response.meta.generatedAt)}</span></div>}
      <section className="mt-8 flex flex-col justify-between gap-5 rounded-2xl border border-white/[0.09] bg-white/[0.03] p-6 sm:flex-row sm:items-center"><div><div className="text-xs font-bold text-slate-300">想用條件找商品？</div><p className="mt-1 text-xs text-slate-600">使用市場、資產類別與關鍵指標縮小研究範圍。</p></div><Link href="/screener" className="text-[13px] font-bold text-[#F5B700]">前往全球篩選器 →</Link></section>
    </div>
  </main>;
}

function ResultRow({ row }: { row: UnifiedSearchResult }) { return <tr className="relative border-t border-white/[0.05] hover:bg-[#F5B700]/[0.035]"><td className="px-5 py-4">{row.publicReady && row.detailHref ? <Link href={row.detailHref} className="font-bold text-white after:absolute after:inset-0">{row.displayName}</Link> : <><span className="font-bold text-slate-300">{row.displayName}</span><span className="ml-2 text-[12px] text-amber-300">目前僅供搜尋，不開放詳細頁</span></>}</td><td className="px-5 py-4 font-mono text-[#F5B700]">{display(row.symbolOrCode, "—")}</td><td className="px-5 py-4"><Badge value={row.assetType} /></td><td className="px-5 py-4 text-slate-300">{display(row.exchange, "—")}</td><td className="px-5 py-4 text-slate-300">{display(row.currency, "—")}</td><td className="px-5 py-4 text-right text-[17px] font-bold">{numberLabel(row.latestValue)}</td><td className="px-5 py-4 text-slate-300">{dateLabel(row.asOfDate)}{row.freshnessStatus === "STALE" ? <span className="ml-2 rounded-full bg-amber-400/10 px-2 py-1 text-[12px] text-amber-200">資料延遲</span> : null}</td></tr>; }
function ResultCard({ row }: { row: UnifiedSearchResult }) { const content=<><div className="flex items-start justify-between gap-3"><div><div className="text-[17px] font-bold text-white">{row.displayName}</div><div className="mt-1 font-mono text-[14px] text-[#F5B700]">{display(row.symbolOrCode, "—")}</div></div><Badge value={row.assetType} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-[14px]"><Info label="市場" value={display(row.market, "—")} /><Info label="幣別" value={display(row.currency, "—")} /><Info label="最新值" value={numberLabel(row.latestValue)} /><Info label="資料日期" value={dateLabel(row.asOfDate)} /></div>{!row.publicReady?<div className="mt-3 text-[12px] text-amber-300">目前僅供搜尋，不開放詳細頁</div>:null}</>; return row.publicReady&&row.detailHref?<Link href={row.detailHref} className="block p-5 hover:bg-white/[0.03]">{content}</Link>:<div className="p-5">{content}</div>; }
function Badge({ value }: { value: string }) { return <span className="inline-flex rounded-full border border-[#F5B700]/20 bg-[#F5B700]/[0.07] px-2 py-1 text-[10px] font-bold text-[#F5B700]">{typeLabels[value as SearchType]??value}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div><div className="mb-1 text-[10px] uppercase text-slate-600">{label}</div><div className="text-slate-300">{value}</div></div>; }
function State({ title, description }: { title: string; description: string }) { return <div className="px-6 py-20 text-center"><div className="text-lg font-bold text-slate-300">{title}</div><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">{description}</p></div>; }
