import Link from "next/link";
import type { ReactNode } from "react";

import { getEtfFilterOptions, getEtfList, type EtfListQuery } from "@/lib/data-platform/web/etfService";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const int = (value: string | undefined, fallback: number) => { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback; };
const statusLabel=(value?:string)=>({CURRENT:"最新",HEALTHY_WAITING:"正常等待",STALE:"資料延遲",UNAVAILABLE:"暫無資料",UNKNOWN:"狀態待確認"}[value??"UNKNOWN"]??"狀態待確認");
const display = (value: string | null | undefined, fallback = "資料未提供") => value?.trim() || fallback;
const numberLabel = (value: number | null, digits = 2) => value === null ? "—" : new Intl.NumberFormat("zh-TW", { maximumFractionDigits: digits }).format(value);
const percentLabel = (value: number | null) => value === null ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(2)}%`;
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("zh-TW", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)) : "—";
const hrefWith = (params: URLSearchParams, changes: Record<string, string | number | null>) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value === null || value === "" ? next.delete(key) : next.set(key, String(value))); return `/etf${next.size ? `?${next}` : ""}`; };

export default async function EtfPage({ searchParams }: { searchParams: SearchParams }) {
  const raw = await searchParams;
  const query = first(raw.q)?.trim() || undefined;
  const exchange = first(raw.exchange)?.trim() || undefined;
  const currency = first(raw.currency)?.trim() || undefined;
  const issuer = first(raw.issuer)?.trim() || undefined;
  const category = first(raw.category)?.trim() || undefined;
  const page = int(first(raw.page), 1);
  const pageSize = Math.min(int(first(raw.pageSize), 50), 200);
  const rawSort = first(raw.sort);
  const sort: EtfListQuery["sort"] = rawSort === "latestPrice" || rawSort === "aum" || rawSort === "performance1Y" ? rawSort : "name";
  const direction: EtfListQuery["direction"] = first(raw.direction) === "desc" ? "desc" : "asc";
  const current = new URLSearchParams();
  Object.entries(raw).forEach(([key, value]) => { const item = first(value); if (item) current.set(key, item); });

  let result: Awaited<ReturnType<typeof getEtfList>> | null = null;
  let options: Awaited<ReturnType<typeof getEtfFilterOptions>> = { exchanges: [], currencies: [], issuers: [], categories: [] };
  let loadError = false;
  try {
    [result, options] = await Promise.all([getEtfList({ query, exchange, currency, issuer, category, page, pageSize, sort, direction }), getEtfFilterOptions()]);
  } catch { loadError = true; }
  const rows = (result?.data ?? []).filter((row) => row.publicReady);
  const pagination = result?.pagination;
  const hasFilters = Boolean(query || exchange || currency || issuer || category);

  return <main className="min-h-screen bg-[#040a18] px-4 pb-20 pt-28 text-white sm:px-6">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[0.08] bg-[#040a18]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1700px] items-center justify-between px-4 sm:px-10"><Link href="/" className="shrink-0"><div className="text-[26px] font-black leading-none">Smart<span className="text-[#F5C542]">Match</span></div><div className="mt-1 text-[10px] text-slate-500">全球投資研究平台</div></Link><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-300 lg:flex"><Link href="/" className="hover:text-white">市場總覽</Link><Link href="/etf" className="text-[#F5C542]">ETF</Link><Link href="/funds" className="hover:text-white">基金</Link><Link href="/compare" className="hover:text-white">商品比較</Link><Link href="/rankings" className="hover:text-white">排行榜</Link></nav><Link href="/search" className="rounded-lg border border-white/20 px-4 py-2 text-[13px] font-semibold text-slate-200 hover:bg-white/[0.06]">搜尋</Link></div></header>
    <div className="mx-auto max-w-[1600px]">
      <section className="mb-8"><div className="mb-3 flex flex-wrap items-center gap-2 text-[11px] font-bold tracking-[0.18em] text-[#F5C542]"><span>全球 ETF 正式資料</span><span className="rounded-full border border-[#F5C542]/25 bg-[#F5C542]/10 px-2 py-1 tracking-normal">資金流向部分涵蓋</span></div><h1 className="text-3xl font-black tracking-tight sm:text-[42px]">全球 ETF 資料庫</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400 sm:text-base">搜尋全球交易所交易基金，查看 正式價格、NAV、資產規模與資料來源。缺少的指標不推算、不補零。</p></section>
      <form action="/etf" className="mb-5 grid gap-3 rounded-2xl border border-white/[0.09] bg-white/[0.025] p-4 md:grid-cols-2 xl:grid-cols-6">
        <label className="xl:col-span-2"><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">關鍵字</span><input name="q" defaultValue={query} placeholder="ETF 名稱、Ticker 或 ISIN" className="w-full rounded-lg border border-white/15 bg-[#071020] px-3 py-2.5 text-sm outline-none placeholder:text-slate-600 focus:border-[#F5C542]" /></label>
        <Filter name="exchange" label="交易所" value={exchange} options={options.exchanges} /><Filter name="currency" label="幣別" value={currency} options={options.currencies} /><Filter name="issuer" label="發行商" value={issuer} options={options.issuers} /><Filter name="category" label="資產類別" value={category} options={options.categories} />
        <input type="hidden" name="sort" value={sort} /><input type="hidden" name="direction" value={direction} /><input type="hidden" name="pageSize" value={pageSize} />
        <div className="flex items-end gap-2 xl:col-start-6"><button className="flex-1 rounded-lg bg-[#F5C542] px-4 py-2.5 text-sm font-bold text-[#0B1220] hover:bg-[#ffd75f]">套用</button>{hasFilters && <Link href="/etf" className="rounded-lg border border-white/15 px-4 py-2.5 text-sm text-slate-300 hover:bg-white/[0.05]">清除</Link>}</div>
      </form>
      <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-slate-500">{loadError ? "ETF 資料暫時無法讀取" : `共 ${pagination?.total.toLocaleString("zh-TW") ?? 0} 檔 ETF · 第 ${pagination?.page ?? page} 頁`}</div><div className="flex flex-wrap items-center gap-2 text-xs"><span className="text-slate-600">排序</span><Sort current={current} active={sort === "name"} field="name" direction={sort === "name" && direction === "asc" ? "desc" : "asc"}>名稱</Sort><Sort current={current} active={sort === "latestPrice"} field="latestPrice" direction={sort === "latestPrice" && direction === "desc" ? "asc" : "desc"}>價格</Sort><Sort current={current} active={sort === "aum"} field="aum" direction={sort === "aum" && direction === "desc" ? "asc" : "desc"}>AUM</Sort><Sort current={current} active={sort === "performance1Y"} field="performance1Y" direction={sort === "performance1Y" && direction === "desc" ? "asc" : "desc"}>1Y 表現</Sort></div></div>
      <section className="overflow-hidden rounded-2xl border border-white/[0.09] bg-white/[0.02]">{loadError ? <Empty title="ETF 資料暫時無法讀取" description="正式資料服務目前未回應；不會改用靜態或模擬資料。" /> : rows.length === 0 ? <Empty title="找不到符合條件的 ETF" description="請調整關鍵字或篩選條件。" /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1450px] text-left"><thead className="bg-white/[0.045] text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">ETF</th><th className="px-4 py-3">交易所</th><th className="px-4 py-3">發行商 / 類別</th><th className="px-4 py-3 text-right">價格</th><th className="px-4 py-3 text-right">NAV</th><th className="px-4 py-3 text-right">溢折價</th><th className="px-4 py-3 text-right">AUM</th><th className="px-4 py-3 text-right">流通單位</th><th className="px-4 py-3 text-right">1Y 表現</th><th className="px-4 py-3">持股</th><th className="px-4 py-3">資金流向</th><th className="px-4 py-3">資料狀態</th></tr></thead><tbody>{rows.map((etf) => <EtfRow key={etf.identity.id} etf={etf} />)}</tbody></table></div><div className="divide-y divide-white/[0.07] md:hidden">{rows.map((etf) => <EtfCard key={etf.identity.id} etf={etf} />)}</div></>}</section>
      {pagination && pagination.total > 0 && <nav className="mt-5 flex items-center justify-between" aria-label="ETF 分頁"><Link aria-disabled={pagination.page <= 1} href={pagination.page > 1 ? hrefWith(current, { page: pagination.page - 1 }) : hrefWith(current, { page: 1 })} className={`rounded-lg border px-4 py-2 text-sm ${pagination.page <= 1 ? "pointer-events-none border-white/[0.06] text-slate-700" : "border-white/15 text-slate-300 hover:bg-white/[0.05]"}`}>← 上一頁</Link><span className="text-xs text-slate-500">每頁 {pagination.pageSize} 筆</span><Link aria-disabled={!pagination.hasNextPage} href={pagination.hasNextPage ? hrefWith(current, { page: pagination.page + 1 }) : hrefWith(current, { page: pagination.page })} className={`rounded-lg border px-4 py-2 text-sm ${!pagination.hasNextPage ? "pointer-events-none border-white/[0.06] text-slate-700" : "border-white/15 text-slate-300 hover:bg-white/[0.05]"}`}>下一頁 →</Link></nav>}
      <div className="mt-8 grid gap-3 text-xs text-slate-500 sm:grid-cols-3"><Info label="資料新鮮度" value={statusLabel(result?.meta.freshnessStatus)} /><Info label="涵蓋狀態" value="ETF 主檔已接線；資金流向為部分涵蓋" /></div>
    </div>
  </main>;
}

function Filter({ name, label, value, options }: { name: string; label: string; value?: string; options: string[] }) { return <label><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">{label}</span><select name={name} defaultValue={value ?? ""} className="w-full rounded-lg border border-white/15 bg-[#071020] px-3 py-2.5 text-sm outline-none focus:border-[#F5C542]"><option value="">全部</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
function Sort({ current, active, field, direction, children }: { current: URLSearchParams; active: boolean; field: EtfListQuery["sort"]; direction: "asc" | "desc"; children: ReactNode }) { return <Link href={hrefWith(current, { sort: field ?? "name", direction, page: 1 })} className={`rounded-full border px-3 py-1.5 ${active ? "border-[#F5C542]/60 bg-[#F5C542]/10 text-[#F5C542]" : "border-white/10 text-slate-400 hover:border-white/25"}`}>{children}{active ? (direction === "asc" ? " ↓" : " ↑") : ""}</Link>; }
type Etf = NonNullable<Awaited<ReturnType<typeof getEtfList>>["data"]>[number];
function EtfRow({ etf }: { etf: Etf }) { return <tr className="border-t border-white/[0.055] text-[12px] hover:bg-[#F5C542]/[0.035]"><td className="px-5 py-4"><Link href={`/etf/${encodeURIComponent(etf.identity.symbol)}`} className="font-bold text-[#F5C542] hover:underline">{etf.identity.symbol}</Link><div className="mt-1 max-w-[260px] text-slate-300">{etf.identity.name}</div></td><td className="px-4 py-4 text-slate-400">{display(etf.identity.market, "—")} · {display(etf.identity.currency, "—")}</td><td className="px-4 py-4"><div className="text-slate-300">{display(etf.issuer)}</div><div className="mt-1 text-[10px] text-slate-600">{display(etf.category, "未分類")}</div></td><Metric value={numberLabel(etf.price, 4)} /><Metric value={numberLabel(etf.nav, 4)} /><Metric value={percentLabel(etf.premiumDiscount)} /><Metric value={numberLabel(etf.aum, 0)} /><Metric value={numberLabel(etf.sharesOutstanding, 0)} /><Metric value={percentLabel(etf.metrics.performance1Y)} tone={etf.metrics.performance1Y} /><td className="px-4 py-4 text-slate-400">{etf.holdingsCount ? `${etf.holdingsCount} 筆` : "—"}</td><td className="px-4 py-4 text-slate-500">{etf.flowCoverage.status}<div className="mt-1 text-[10px]">{dateLabel(etf.flowCoverage.asOfDate)}</div></td><td className="px-4 py-4"><Status value={etf.freshnessStatus} /></td></tr>; }
function EtfCard({ etf }: { etf: Etf }) { return <article className="p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/etf/${encodeURIComponent(etf.identity.symbol)}`} className="font-black text-[#F5C542]">{etf.identity.symbol}</Link><h2 className="mt-1 font-semibold text-white">{etf.identity.name}</h2><p className="mt-1 text-[10px] text-slate-600">{display(etf.identity.market, "—")} · {display(etf.identity.currency, "—")}</p></div><Status value={etf.freshnessStatus} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Info label="發行商" value={display(etf.issuer)} /><Info label="資產類別" value={display(etf.category, "未分類")} /><Info label="最新價格" value={numberLabel(etf.price, 4)} /><Info label="NAV" value={numberLabel(etf.nav, 4)} /><Info label="溢折價" value={percentLabel(etf.premiumDiscount)} /><Info label="AUM" value={numberLabel(etf.aum, 0)} /><Info label="流通單位" value={numberLabel(etf.sharesOutstanding, 0)} /><Info label="1Y 表現" value={percentLabel(etf.metrics.performance1Y)} /></div><p className="mt-4 border-t border-white/[0.06] pt-3 text-[10px] text-slate-600">持股：{etf.holdingsCount || "—"} · 資金流向：{etf.flowCoverage.status}</p></article>; }
function Metric({ value, tone }: { value: string; tone?: number | null }) { return <td className={`px-4 py-4 text-right font-semibold ${tone === undefined || tone === null ? "text-slate-200" : tone >= 0 ? "text-emerald-400" : "text-red-400"}`}>{value}</td>; }
function Status({ value }: { value: string }) { const healthy = value === "CURRENT" || value === "HEALTHY_WAITING"; return <span className={`inline-flex rounded-full border px-2 py-1 text-[9px] font-bold ${healthy ? "border-emerald-500/25 bg-emerald-500/10 text-emerald-400" : "border-white/10 bg-white/[0.04] text-slate-500"}`}>{value}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div><div className="mb-1 text-[10px] uppercase tracking-wide text-slate-600">{label}</div><div className="text-slate-300">{value}</div></div>; }
function Empty({ title, description }: { title: string; description: string }) { return <div className="px-6 py-20 text-center"><div className="text-lg font-bold">{title}</div><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">{description}</p></div>; }

