import Link from "next/link";
import { HistoricalChartClient } from "./HistoricalChartClient";
import { StockResearchTabs } from "./StockResearchTabs";
import type { DetailData, Metric, ResearchSection } from "./UniversalAssetDetail";

const get=(xs:Metric[],label:string)=>xs.find(x=>x.label===label)?.value??"—";
const positive=(v:string)=>!v.startsWith("-")&&v!=="—";
const signed=(v:string)=>{const n=Number(v.replace(/,/g,""));return Number.isFinite(n)&&n>0?`+${v}`:v};
const unit=(c?:string)=>c==="TWD"?"元":c==="USD"?"美元":c??"";
const volume=(raw:string)=>{const n=Number(raw.replace(/,/g,""));return !Number.isFinite(n)?raw:n>=1e8?`${(n/1e8).toFixed(2)} 億股`:n>=1e6?`${(n/1e6).toFixed(2)} 百萬股`:`${n.toLocaleString("zh-TW")} 股`};
const compact=(raw:string,c?:string)=>{const n=Number(raw.replace(/[^\d.-]/g,""));if(!Number.isFinite(n))return raw;const u=c==="USD"?"美元":"元";return n>=1e12?`${(n/1e12).toFixed(2)} 兆${u}`:n>=1e8?`${(n/1e8).toFixed(2)} 億${u}`:`${n.toLocaleString("zh-TW")} ${u}`};
const freshness=(v?:DetailData["freshnessStatus"])=>({LATEST:"資料最新",STALE:"資料延遲",SOURCE_WAIT:"等待資料發布",PARTIAL:"部分可用",NOT_AVAILABLE:"暫無資料",UNKNOWN:"狀態待確認"}[v??"UNKNOWN"]);

export function StockDetailExperience({data}:{data:DetailData}){
 const u=unit(data.currency),change=get(data.summary,"漲跌點"),pct=get(data.summary,"漲跌幅"),industry=data.keyData.filter(x=>["產業類別","細分產業"].includes(x.label));
 const snapshot=[{label:"開盤",value:get(data.summary,"開盤")},{label:"最高",value:get(data.summary,"最高")},{label:"最低",value:get(data.summary,"最低")},{label:"前收",value:get(data.summary,"前收")},{label:"成交量",value:get(data.summary,"成交量")},{label:"成交額",value:get(data.summary,"成交額（收盤價×成交量）")},{label:"52 週高點",value:get(data.summary,"52週高點")},{label:"52 週低點",value:get(data.summary,"52週低點")}];
 const research=(data.research??[]).filter(x=>!["overview","source","related"].includes(x.id));
 return <main className="min-h-screen bg-[#07111f] text-white"><Header/><div className="mx-auto max-w-[1480px] px-4 py-6 sm:px-6 md:px-10">
  <section className="rounded-2xl border border-[#c99b35]/25 bg-gradient-to-br from-[#142740] to-[#0b1728] p-5 shadow-2xl md:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2 text-sm text-slate-300"><span className="rounded-full bg-[#F5B700]/10 px-3 py-1 font-bold text-[#ffe18a]">股票</span><strong className="text-white">{data.code}</strong><span>｜</span><span>{data.exchange}</span><span>｜</span><span>{data.currency}</span><span className={`rounded-full px-3 py-1 font-bold ${data.freshnessStatus==="LATEST"?"bg-emerald-400/15 text-emerald-200":"bg-amber-400/15 text-amber-100"}`}>{freshness(data.freshnessStatus)}｜{data.priceDate?.replaceAll("-","/")??"日期待確認"}</span></div><h1 className="mt-3 text-3xl font-black md:text-4xl">{data.name}</h1>{data.officialName&&data.officialName!==data.name?<p className="mt-1 text-sm text-slate-400">{data.officialName}</p>:null}{industry.length?<p className="mt-2 text-sm text-slate-300">{industry.map(x=>x.value).join(" ／ ")}</p>:null}</div><div className="lg:text-right"><div className="text-4xl font-black tabular-nums md:text-5xl">{get(data.summary,"最新價格")} <span className="text-xl text-slate-300">{u}</span></div><div className={`mt-2 text-lg font-black ${positive(change)?"text-rose-300":"text-emerald-300"}`}>{signed(change)} {u}（{signed(pct)}）</div><div className="mt-2 text-sm text-slate-300">{data.priceDate?.replaceAll("-","/")} 收盤 · {freshness(data.freshnessStatus)}</div></div></div>
  <div className="mt-6 grid grid-cols-2 gap-x-5 gap-y-4 border-t border-slate-500/25 pt-5 sm:grid-cols-4 xl:grid-cols-8">{snapshot.map(x=><Metric key={x.label} {...x}/>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-500/20 pt-4 text-sm text-slate-300"><span>市值 <strong className="ml-2 text-white">{get(data.summary,"市值")}</strong></span><span>最後更新：{data.lastUpdated??data.updatedAt??"—"} · {data.frequency??"—"}</span><div className="flex gap-2"><Link href={`/compare?asset=${encodeURIComponent(data.code)}`} className="rounded-lg border border-slate-400/35 px-4 py-2 font-bold text-white">加入比較</Link><Link href="/markets" className="rounded-lg bg-[#F5B700] px-4 py-2 font-black text-[#07111f]">查看市場</Link></div></div></section>
  <div className="mt-6"><HistoricalChartClient points={data.history}/></div>{data.performance.length?<Performance metrics={data.performance}/>:null}<div className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]">{data.risk.length?<Risk metrics={data.risk}/>:null}<Fundamentals research={data.research??[]} marketCap={get(data.summary,"市值")}/></div>{research.length?<StockResearchTabs sections={research}/>:null}<section className="mt-6 rounded-2xl border border-slate-500/25 bg-[#102039] p-5"><h2 className="text-xl font-black">資料概況</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><Info label="最後更新" value={data.lastUpdated??data.updatedAt??"—"}/><Info label="更新頻率" value={data.frequency??"—"}/><Info label="歷史範圍" value={data.historyRows?`${data.earliestHistory} 至 ${data.latestHistory}（${data.historyRows.toLocaleString("zh-TW")} 筆）`:"—"}/></div></section>
 </div></main>;
}
function Header(){return <header className="border-b border-slate-600/30"><div className="mx-auto flex min-h-16 max-w-[1480px] items-center justify-between px-5"><Link href="/" className="text-2xl font-black">Smart<span className="text-[#F5B700]">Match</span></Link><nav className="hidden gap-6 text-sm font-semibold text-slate-300 md:flex"><Link href="/markets">市場總覽</Link><Link href="/compare">商品比較</Link><Link href="/portfolio">投資組合</Link></nav><Link href="/search" className="rounded-lg border border-slate-400/35 px-4 py-2 text-sm font-bold">搜尋商品</Link></div></header>}
function Metric({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold text-slate-400">{label}</div><div className="mt-1 text-lg font-black tabular-nums">{value}</div></div>}
function Performance({metrics}:{metrics:Metric[]}){return <section className="mt-6 rounded-2xl border border-slate-500/25 bg-[#102039] p-5"><h2 className="text-xl font-black">期間績效</h2><div className="mt-4 flex gap-3 overflow-x-auto">{metrics.map(x=><div key={x.label} className="min-w-[125px] flex-1 border-r border-slate-500/25 last:border-0"><div className="text-sm text-slate-400">{x.label}</div><div className={`mt-1 text-2xl font-black ${positive(x.value)?"text-rose-300":"text-emerald-300"}`}>{x.value}</div></div>)}</div></section>}
function Risk({metrics}:{metrics:Metric[]}){return <section className="rounded-2xl border border-slate-500/25 bg-[#102039] p-5"><h2 className="text-xl font-black">風險觀察</h2><div className="mt-5 space-y-5">{metrics.map(x=>{const n=Math.min(100,Math.abs(Number(x.value.replace(/[^\d.-]/g,"")))||0);return <div key={x.label}><div className="flex items-end justify-between"><span className="text-sm font-bold text-slate-300">{x.label}</span><strong className="text-2xl">{x.value}</strong></div><div className="mt-2 h-1.5 rounded-full bg-slate-700"><div className="h-full rounded-full bg-[#F5B700]" style={{width:`${n}%`}}/></div></div>})}</div><p className="mt-5 text-xs leading-5 text-slate-400">波動與回撤描述歷史價格風險，不代表未來報酬。</p></section>}
function Fundamentals({research,marketCap}:{research:ResearchSection[];marketCap:string}){const f=research.find(x=>x.id==="financial")?.metrics??[],v=research.find(x=>x.id==="valuation")?.metrics??[];const pick=(a:Metric[],keys:string[])=>a.filter(x=>keys.includes(x.label));const groups=[{title:"營運與獲利",items:pick(f,["營收","每股盈餘","毛利率","營業利益率","淨利率"])},{title:"資本效率",items:pick(f,["股東權益報酬率","資產報酬率","營業現金流","自由現金流"])},{title:"市場估值",items:[...pick(v,["本益比","預估本益比","股價淨值比","股價營收比","股息殖利率"]),{label:"市值",value:marketCap}]}].filter(x=>x.items.length);return <section className="rounded-2xl border border-slate-500/25 bg-[#102039] p-5"><h2 className="text-xl font-black">基本面摘要</h2><div className="mt-4 divide-y divide-slate-500/20">{groups.map(g=><div key={g.title} className="py-4 first:pt-0"><h3 className="text-sm font-black text-[#ffe18a]">{g.title}</h3><div className="mt-3 grid grid-cols-2 gap-4">{g.items.map(x=><Metric key={x.label} {...x}/>)}</div></div>)}</div></section>}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold text-slate-400">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}