ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS asset_class TEXT NOT NULL DEFAULT 'OTHER';
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS root_id UUID;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS contract_year INTEGER;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS first_trade_date DATE;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS last_trade_date DATE;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS final_settlement_date DATE;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS delivery_month TEXT;
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE futures_contracts ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE futures_contracts ALTER COLUMN expiration DROP NOT NULL;
ALTER TABLE futures_observations ALTER COLUMN settlement DROP NOT NULL;
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS asset_class TEXT NOT NULL DEFAULT 'OTHER';
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS open NUMERIC(24,8);
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS high NUMERIC(24,8);
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS low NUMERIC(24,8);
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS close NUMERIC(24,8);
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS volume BIGINT;
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS open_interest BIGINT;
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS source_record_id TEXT;
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS quality_status TEXT NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE futures_observations ADD COLUMN IF NOT EXISTS freshness_status TEXT NOT NULL DEFAULT 'UNKNOWN';
UPDATE futures_contracts SET asset_class='COMMODITY_FUTURES',verification_status='VERIFIED' WHERE exchange='COMEX' AND contract_symbol='GCQ26';
UPDATE futures_contracts SET asset_class='INTEREST_RATE_FUTURES',verification_status='VERIFIED' WHERE exchange='OSE' AND contract_symbol='FUT_TOA3M_260915';
UPDATE futures_observations o SET asset_class=c.asset_class,verification_status=c.verification_status FROM futures_contracts c WHERE c.id=o.contract_id;
CREATE INDEX IF NOT EXISTS futures_contracts_asset_root_month_idx ON futures_contracts(asset_class,root_symbol,contract_month);
CREATE INDEX IF NOT EXISTS futures_observations_asset_observed_idx ON futures_observations(asset_class,observed_at);

CREATE TABLE IF NOT EXISTS commodity_identities (id UUID PRIMARY KEY, official_name TEXT NOT NULL, display_name TEXT NOT NULL, commodity_group TEXT NOT NULL, commodity_subgroup TEXT NOT NULL, unit_of_measure TEXT, primary_currency TEXT, region TEXT, country TEXT, status TEXT NOT NULL, source TEXT NOT NULL, source_url TEXT, verification_status TEXT NOT NULL, license_status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(official_name));
CREATE TABLE IF NOT EXISTS futures_product_roots (id UUID PRIMARY KEY, commodity_id UUID NOT NULL REFERENCES commodity_identities(id), asset_class TEXT NOT NULL, official_product_name TEXT NOT NULL, root_symbol TEXT NOT NULL, exchange TEXT NOT NULL, mic TEXT, currency TEXT NOT NULL, country TEXT, jurisdiction TEXT, timezone TEXT NOT NULL, status TEXT NOT NULL, source TEXT NOT NULL, source_url TEXT, verification_status TEXT NOT NULL, license_status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(asset_class,exchange,root_symbol));
ALTER TABLE futures_contracts ADD CONSTRAINT futures_contracts_root_id_fkey FOREIGN KEY(root_id) REFERENCES futures_product_roots(id) NOT VALID;
CREATE TABLE IF NOT EXISTS futures_contract_specifications (id UUID PRIMARY KEY, root_id UUID NOT NULL REFERENCES futures_product_roots(id), contract_size NUMERIC(24,8) NOT NULL, contract_unit TEXT NOT NULL, quotation_unit TEXT NOT NULL, currency TEXT NOT NULL, minimum_tick NUMERIC(24,8) NOT NULL, tick_value NUMERIC(24,8), settlement_type TEXT NOT NULL, delivery_type TEXT NOT NULL, delivery_location TEXT, grade_specification TEXT, expiration_rule TEXT NOT NULL, last_trade_rule TEXT, first_notice_rule TEXT, last_notice_rule TEXT, source TEXT NOT NULL, source_url TEXT, as_of_date DATE, verification_status TEXT NOT NULL, license_status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(root_id));
CREATE TABLE IF NOT EXISTS futures_contract_events (id UUID PRIMARY KEY, contract_id UUID NOT NULL REFERENCES futures_contracts(id), asset_class TEXT NOT NULL, event_type TEXT NOT NULL, event_date DATE, applicability TEXT NOT NULL, source TEXT NOT NULL, source_record_id TEXT, source_url TEXT, verification_status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(contract_id,event_type));
CREATE TABLE IF NOT EXISTS futures_settlements (id UUID PRIMARY KEY, contract_id UUID NOT NULL REFERENCES futures_contracts(id), settlement_date DATE NOT NULL, settlement_price NUMERIC(24,8) NOT NULL, settlement_type TEXT NOT NULL, source TEXT NOT NULL, source_record_id TEXT, source_url TEXT, verification_status TEXT NOT NULL, ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(contract_id,settlement_date,source));
CREATE TABLE IF NOT EXISTS futures_continuous_series (id UUID PRIMARY KEY, root_id UUID NOT NULL REFERENCES futures_product_roots(id), series_code TEXT NOT NULL UNIQUE, roll_rule TEXT NOT NULL, adjustment_method TEXT NOT NULL, frequency TEXT NOT NULL, calculation_method TEXT NOT NULL, source_type TEXT NOT NULL, status TEXT NOT NULL, calculated_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS futures_roll_events (id UUID PRIMARY KEY, continuous_series_id UUID NOT NULL REFERENCES futures_continuous_series(id), from_contract_id UUID NOT NULL REFERENCES futures_contracts(id), to_contract_id UUID NOT NULL REFERENCES futures_contracts(id), roll_date DATE NOT NULL, roll_rule TEXT NOT NULL, roll_reason TEXT NOT NULL, from_price NUMERIC(24,8), to_price NUMERIC(24,8), adjustment NUMERIC(24,8), calculation_method TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(continuous_series_id,roll_date));
CREATE TABLE IF NOT EXISTS futures_front_contracts (root_id UUID PRIMARY KEY REFERENCES futures_product_roots(id), active_contract_id UUID NOT NULL REFERENCES futures_contracts(id), selection_rule TEXT NOT NULL, current_settlement NUMERIC(24,8), as_of_date DATE NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS commodity_futures_coverage (root_id UUID PRIMARY KEY REFERENCES futures_product_roots(id), asset_class_status TEXT NOT NULL, commodity_identity_status TEXT NOT NULL, root_identity_status TEXT NOT NULL, listed_contract_count INTEGER NOT NULL DEFAULT 0, specification_status TEXT NOT NULL, current_contract_status TEXT NOT NULL, history_status TEXT NOT NULL, history_first_date DATE, history_last_date DATE, ohlc_status TEXT NOT NULL, settlement_status TEXT NOT NULL, volume_status TEXT NOT NULL, open_interest_status TEXT NOT NULL, lifecycle_status TEXT NOT NULL, continuous_status TEXT NOT NULL, roll_audit_status TEXT NOT NULL, taxonomy_status TEXT NOT NULL, provenance_status TEXT NOT NULL, freshness_status TEXT NOT NULL, license_status TEXT NOT NULL, coverage_status TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS commodity_futures_runner_progress (id UUID PRIMARY KEY, run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), new_contracts INTEGER NOT NULL, new_observations INTEGER NOT NULL, updated_observations INTEGER NOT NULL, no_op_current INTEGER NOT NULL, failed INTEGER NOT NULL, scope TEXT NOT NULL);
