import { prisma } from "@/lib/prisma";
const headers={"Access-Control-Allow-Origin":"*","Cache-Control":"no-store"};
export async function GET(request:Request){const q=new URL(request.url).searchParams,type=q.get('type')?.toUpperCase(),productId=q.get('productId'),securityId=q.get('securityId'),ticker=q.get('ticker'),radar=q.get('scope')==='radar';if(type&&!['ETF','FUND'].includes(type))return Response.json({error:'type must be ETF or FUND'},{status:400,headers});// Official 331-ETF snapshot (source='ETF_OFFICIAL_DAILY_SNAPSHOT') is the canonical holdings layer
// for any TW ETF it covers. For an etf_id that has ANY official-snapshot rows, both the "latest date"
// resolution and the final row set are restricted to that source only, so the older/legacy holdings
// writer for the same etf_id+date can never mix in and duplicate/conflict with it. An etf_id the
// official engine has never reached falls back to whatever existed before — unchanged behavior.
const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`WITH etf_official AS(SELECT DISTINCT etf_id FROM holdings WHERE etf_id IS NOT NULL AND source='ETF_OFFICIAL_DAILY_SNAPSHOT'),latest AS(SELECT COALESCE(h.etf_id,h.fund_id) product_id,max(h.as_of_date) as_of_date FROM holdings h WHERE ($1::text IS NULL OR ($1='ETF' AND h.etf_id IS NOT NULL) OR ($1='FUND' AND h.fund_id IS NOT NULL)) AND (h.etf_id IS NULL OR NOT EXISTS(SELECT 1 FROM etf_official eo WHERE eo.etf_id=h.etf_id) OR h.source='ETF_OFFICIAL_DAILY_SNAPSHOT') GROUP BY COALESCE(h.etf_id,h.fund_id)) SELECT h.*,e.code AS etf_code,e.name AS etf_name,f.code AS fund_code,f.name AS fund_name,s.industry FROM holdings h JOIN latest l ON l.product_id=COALESCE(h.etf_id,h.fund_id) AND l.as_of_date=h.as_of_date LEFT JOIN etfs e ON e.id=h.etf_id LEFT JOIN funds f ON f.id=h.fund_id LEFT JOIN securities s ON s.id=h.security_id WHERE ($2::text IS NULL OR COALESCE(h.etf_id,h.fund_id)=$2) AND ($3::text IS NULL OR h.security_id=$3) AND ($4::text IS NULL OR h.ticker=$4) AND ($5::boolean=false OR (h.etf_id IS NOT NULL AND e.currency='TWD' AND e.exchange IN ('TWSE','TPEx','TPEX','TW')) OR (h.fund_id IS NOT NULL AND f.data_provider='MoneyDJ')) AND (h.etf_id IS NULL OR NOT EXISTS(SELECT 1 FROM etf_official eo2 WHERE eo2.etf_id=h.etf_id) OR h.source='ETF_OFFICIAL_DAILY_SNAPSHOT') ORDER BY COALESCE(e.code,f.code),h.rank NULLS LAST LIMIT 20000`,type??null,productId,securityId,ticker,radar);return Response.json({data:rows,meta:{currentOnly:true,rows:rows.length}},{headers})}
export async function OPTIONS(){return new Response(null,{status:204,headers})}
