import { prisma } from "@/lib/prisma";
import { resolveFundHoldings } from "@/scripts/data/global-fund/services/fund-holdings-resolution";
export const runtime="nodejs";export const dynamic="force-dynamic";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
type T="ETF"|"FUND";type R={product_id:string;product_name:string;product_type:T;security_id:string|null;security_name:string;ticker:string|null;isin:string|null;market:string|null;country:string|null;weight:unknown;holdings_as_of:Date|null;source:string;retrieved_at:Date|null};
const norm=(v:string)=>v.normalize("NFKC").trim().toUpperCase().replace(/[^\p{L}\p{N}]/gu,"");
const output=(r:R)=>({canonical_product_id:r.product_id,product_id:r.product_id,product_name:r.product_name,product_type:r.product_type,security_id:r.security_id,security_name:r.security_name,ticker:r.ticker,isin:r.isin,market:r.market,country:r.country,weight:r.weight==null?null:Number(r.weight),holdings_as_of:r.holdings_as_of?.toISOString().slice(0,10)??null,source:r.source,retrieved_at:r.retrieved_at?.toISOString()??null});
function result(rows:R[],requested:string[]){const products=new Map<string,any>();for(const row of rows){const key=`${row.product_type}:${row.product_id}`,item=products.get(key)??{product_id:row.product_id,product_name:row.product_name,product_type:row.product_type,matched_count:0,matched_weight_sum:0,matched_holdings:[]},holding=output(row);item.matched_holdings.push(holding);item.matched_count++;item.matched_weight_sum+=holding.weight??0;products.set(key,item)}return Response.json({data:{requested,products:[...products.values()].sort((a,b)=>b.matched_count-a.matched_count||b.matched_weight_sum-a.matched_weight_sum)},error:null},{headers:{...cors,"Cache-Control":"private, max-age=30"}})}
async function etfs(productId:string|null,securityId:string|null,tokens:string[],names:string[]):Promise<R[]>{return prisma.$queryRawUnsafe<R[]>(`WITH ranked AS (SELECT s.*,row_number() OVER(PARTITION BY s.etf_id ORDER BY (s.effective_date IS NOT NULL) DESC,s.effective_date DESC NULLS LAST,(s.quality_status='PASS') DESC,(s.completeness_status='COMPLETE') DESC,s.canonical_row_count DESC,s.retrieved_at DESC,s.id) rn FROM etf_holding_snapshots s WHERE s.canonical_row_count>0) SELECT e.id product_id,e.name product_name,'ETF'::text product_type,r.security_id,COALESCE(sec.name,r.holding_name) security_name,COALESCE(sec.ticker,r.ticker) ticker,COALESCE(sec.isin,r.isin) isin,e.exchange market,COALESCE(sec.country,r.country) country,r.weight,s.effective_date holdings_as_of,s.source,s.retrieved_at FROM ranked s JOIN etf_holdings r ON r.snapshot_id=s.id JOIN etfs e ON e.id=s.etf_id LEFT JOIN securities sec ON sec.id=r.security_id WHERE s.rn=1 AND ($1::text IS NULL OR e.id=$1 OR e.code=$1 OR e.isin=$1) AND ($2::text IS NULL OR r.security_id=$2) AND (cardinality(string_to_array($3,','))=0 OR upper(COALESCE(sec.ticker,r.ticker,''))=ANY(string_to_array($3,',')) OR upper(regexp_replace(COALESCE(sec.name,r.holding_name),'[^[:alnum:]]','','g'))=ANY(string_to_array($4,','))) ORDER BY e.id,r.id LIMIT 5000`,productId,securityId,tokens.join(","),names.join(","))}
async function funds(productId:string|null,securityId:string|null,tokens:string[],names:string[]):Promise<R[]>{
 if(productId){const [fund]=await prisma.$queryRawUnsafe<Array<{id:string;name:string}>>(`SELECT id,name FROM funds WHERE id=$1 OR code=$1 OR isin=$1 LIMIT 1`,productId);if(!fund)return[];const resolved=await resolveFundHoldings(prisma,fund.id);if(!resolved)return[];return(resolved.holdings as Array<Record<string,unknown>>).filter(row=>(!securityId||row.security_id===securityId)&&(!tokens.length||tokens.includes(String(row.security_ticker??row.ticker??row.holding_code??"").toUpperCase())||names.includes(norm(String(row.security_name??row.holding_name??""))))).map(row=>({product_id:fund.id,product_name:fund.name,product_type:"FUND",security_id:row.security_id as string|null,security_name:String(row.security_name??row.holding_name),ticker:(row.security_ticker??row.ticker??row.holding_code??null) as string|null,isin:row.isin as string|null,market:null,country:(row.security_country??row.country??null) as string|null,weight:row.weight,holdings_as_of:resolved.as_of_date,source:resolved.source,retrieved_at:resolved.retrieved_at}))}
 return prisma.$queryRawUnsafe<R[]>(`WITH snapshots AS (SELECT fund_id,source,filing_id,as_of_date,max(created_at) retrieved_at,count(*) rows,row_number() OVER(PARTITION BY fund_id ORDER BY as_of_date DESC,count(*) DESC,source,filing_id) rn FROM holdings WHERE asset_type='FUND' AND share_class_id IS NULL GROUP BY fund_id,source,filing_id,as_of_date) SELECT f.id product_id,f.name product_name,'FUND'::text product_type,h.security_id,COALESCE(sec.name,h.holding_name) security_name,COALESCE(sec.ticker,h.ticker,h.holding_code) ticker,COALESCE(sec.isin,h.isin) isin,NULL::text market,COALESCE(sec.country,h.country) country,h.weight,h.as_of_date holdings_as_of,h.source,s.retrieved_at FROM snapshots s JOIN holdings h ON h.fund_id=s.fund_id AND h.source=s.source AND h.filing_id=s.filing_id JOIN funds f ON f.id=h.fund_id LEFT JOIN securities sec ON sec.id=h.security_id WHERE s.rn=1 AND ($1::text IS NULL OR h.security_id=$1) AND (cardinality(string_to_array($2,','))=0 OR upper(COALESCE(sec.ticker,h.ticker,h.holding_code,''))=ANY(string_to_array($2,',')) OR upper(regexp_replace(COALESCE(sec.name,h.holding_name),'[^[:alnum:]]','','g'))=ANY(string_to_array($3,','))) ORDER BY f.id,h.id LIMIT 5000`,securityId,tokens.join(","),names.join(","))}
export function OPTIONS(){return new Response(null,{status:204,headers:cors})}
export async function GET(request:Request){try{const q=new URL(request.url).searchParams,productId=q.get("productId")?.trim()||null,securityId=q.get("securityId")?.trim()||null,type=q.get("type")?.toUpperCase() as T|undefined;if(type&&type!=="ETF"&&type!=="FUND")return Response.json({data:null,error:{code:"INVALID_TYPE"}},{status:400,headers:cors});const tokens=[...new Set([q.get("ticker"),...(q.get("tickers")?.split(",")??[])].map(v=>v?.trim().toUpperCase()).filter((v):v is string=>Boolean(v)))];if(tokens.length>20)return Response.json({data:null,error:{code:"TOO_MANY_TICKERS"}},{status:400,headers:cors});if(!productId&&!securityId&&!tokens.length)return Response.json({data:null,error:{code:"QUERY_REQUIRED"}},{status:400,headers:cors});const aliases=tokens.length?await prisma.$queryRawUnsafe<Array<{name:string;name_en:string|null}>>(`SELECT name,name_en FROM securities WHERE upper(ticker)=ANY(string_to_array($1,','))`,tokens.join(",")):[];const names=[...new Set([...tokens.map(norm),...aliases.flatMap(row=>[row.name,row.name_en].filter((value):value is string=>Boolean(value)).map(norm))])];const rows=[...(type==="FUND"?[]:await etfs(productId,securityId,tokens,names)),...(type==="ETF"?[]:await funds(productId,securityId,tokens,names))];return result(rows,tokens)}catch(error){return Response.json({data:null,error:{code:"CURRENT_HOLDINGS_QUERY_FAILED",message:error instanceof Error?error.message:String(error)}},{status:500,headers:cors})}}
