ALTER TABLE "currency_index_observation_meta"
  ADD COLUMN IF NOT EXISTS "retrieved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "parser_version" TEXT NOT NULL DEFAULT 'UNSPECIFIED',
  ADD COLUMN IF NOT EXISTS "checksum" TEXT,
  ADD COLUMN IF NOT EXISTS "checksum_status" TEXT NOT NULL DEFAULT 'UNAVAILABLE';
