import { randomUUID } from 'node:crypto';
import { getAccountForRequest } from '@/lib/auth/userService';
import { prisma } from '@/lib/prisma';
import type { Prisma } from '@prisma/client';
import { isPublicReadyAsset } from '@/lib/data-platform/web/publicReadiness';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
const TYPES = ['STOCK','ETF','FUND','INDEX','DERIVATIVES','FIXED_INCOME','FX','MACRO','COMMODITY','CRYPTO'] as const;
const TX = ['BUY','SELL','DIVIDEND','INTEREST','FEE','TAX','DEPOSIT','WITHDRAWAL','TRANSFER_IN','TRANSFER_OUT','SPLIT','ADJUSTMENT'] as const;
const body = (r: Request) => r.json().catch(() => ({})) as Promise<Record<string, unknown>>;
const text = (v: unknown, n=200) => typeof v === 'string' && v.trim() ? v.trim().slice(0,n) : null;
const num = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : typeof v === 'string' && v.trim() && Number.isFinite(Number(v)) ? Number(v) : null;
const ok = (data: unknown, status=200) => Response.json({data,error:null},{status,headers:{'Cache-Control':'no-store'}});
const bad = (message: string, status=400) => Response.json({data:null,error:{message}},{status});
async function owner(r: Request) { const a=await getAccountForRequest(r); if(!a) throw new Error('AUTH'); return a; }
async function owned(id: string,userId: string){ return prisma.portfolio.findFirst({where:{id,userId,archivedAt:null}}); }
const include = {items:true,transactions:{orderBy:{occurredAt:'desc' as const},take:250},cashBalances:true,valuations:{orderBy:{asOf:'desc' as const},take:250}};
const cashDelta = (type:string,amount:number,fees:number,tax:number) => type==='BUY'||['FEE','TAX','WITHDRAWAL','TRANSFER_OUT'].includes(type)?-(amount+fees+tax):type==='SELL'?amount-fees-tax:amount;
async function rebuild(tx: Prisma.TransactionClient, portfolioId:string) {
  await tx.portfolioTaxLot.deleteMany({where:{portfolioId}}); await tx.portfolioItem.deleteMany({where:{portfolioId}}); await tx.portfolioCashBalance.deleteMany({where:{portfolioId}});
  const rows=await tx.portfolioTransaction.findMany({where:{portfolioId},orderBy:[{occurredAt:'asc'},{createdAt:'asc'}]});
  for(const row of rows){const amount=Number(row.amount),fees=Number(row.fees),tax=Number(row.tax);await tx.portfolioCashBalance.upsert({where:{portfolioId_currency:{portfolioId,currency:row.currency}},create:{id:randomUUID(),portfolioId,currency:row.currency,balance:cashDelta(row.type,amount,fees,tax)},update:{balance:{increment:cashDelta(row.type,amount,fees,tax)}}});
    if(row.type==='BUY'&&row.assetType&&row.assetId&&row.quantity){const quantity=Number(row.quantity),basis=amount+fees+tax;await tx.portfolioTaxLot.create({data:{id:randomUUID(),portfolioId,transactionId:row.id,assetType:row.assetType,assetId:row.assetId,acquiredAt:row.occurredAt,originalQuantity:quantity,remainingQuantity:quantity,unitCost:basis/quantity,currency:row.currency,fxRateToBase:row.fxRateToBase}});const old=await tx.portfolioItem.findFirst({where:{portfolioId,assetType:row.assetType,assetId:row.assetId}}),oldQty=Number(old?.shares??0),oldBasis=Number(old?.costBasis??0);old?await tx.portfolioItem.update({where:{id:old.id},data:{shares:oldQty+quantity,costBasis:oldBasis+basis,avgCost:(oldBasis+basis)/(oldQty+quantity)}}):await tx.portfolioItem.create({data:{portfolioId,assetType:row.assetType,assetId:row.assetId,assetCode:row.assetId,assetName:row.assetId,shares:quantity,costBasis:basis,avgCost:basis/quantity,currency:row.currency}});}}
}

export async function GET(r: Request){try{const a=await owner(r);const id=new URL(r.url).searchParams.get('id');if(id){const row=await prisma.portfolio.findFirst({where:{id,userId:a.id,archivedAt:null},include});return row?ok(row):bad('Portfolio not found.',404);}return ok(await prisma.portfolio.findMany({where:{userId:a.id,archivedAt:null},orderBy:[{isDefault:'desc'},{createdAt:'asc'}],include}));}catch(e){return bad(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to load portfolios.',e instanceof Error&&e.message==='AUTH'?401:500)}}

export async function POST(r: Request){try{const a=await owner(r),b=await body(r),action=text(b.action,30)??'CREATE';if(action==='CREATE'){const name=text(b.name,80);if(!name)return bad('Name is required.');const count=await prisma.portfolio.count({where:{userId:a.id,archivedAt:null}});return ok(await prisma.portfolio.create({data:{userId:a.id,name,description:text(b.description,500),currency:text(b.currency,3)?.toUpperCase()??'USD',isDefault:count===0,benchmarkAssetType:TYPES.includes(b.benchmarkAssetType as never)?b.benchmarkAssetType as never:undefined,benchmarkAssetId:text(b.benchmarkAssetId),settings:{performance:['TWR','XIRR'],xray:true,events:true,entitlementReady:true}}}),201);}
const portfolioId=text(b.portfolioId),type=text(b.type,30)?.toUpperCase(),currency=text(b.currency,3)?.toUpperCase();if(action!=='ADD_TRANSACTION'||!portfolioId||!type||!currency||!TX.includes(type as never)||!await owned(portfolioId,a.id))return bad('Invalid transaction.');const assetType=text(b.assetType,30)?.toUpperCase(),assetId=text(b.assetId),quantity=num(b.quantity),price=num(b.price),fees=num(b.fees)??0,tax=num(b.tax)??0,rawAmount=num(b.amount);if(['BUY','SELL'].includes(type)&&(!assetType||!TYPES.includes(assetType as never)||!assetId||quantity===null||quantity<=0||price===null||price<0))return bad('Trade requires canonical asset, quantity and price.');if(['BUY','SELL'].includes(type)&&assetType&&assetId&&!await isPublicReadyAsset(assetType,assetId))return bad('Asset is not public ready.',409);const amount=rawAmount??((quantity??0)*(price??0));const result=await prisma.$transaction(async tx=>{const t=await tx.portfolioTransaction.create({data:{id:randomUUID(),portfolioId,type:type as never,assetType:assetType as never,assetId,quantity,price,amount,fees,tax,currency,fxRateToBase:num(b.fxRateToBase),occurredAt:new Date(text(b.occurredAt)??Date.now()),note:text(b.note,1000),idempotencyKey:text(b.idempotencyKey)}});const cashDelta=type==='BUY'||['FEE','TAX','WITHDRAWAL','TRANSFER_OUT'].includes(type)?-(amount+fees+tax):type==='SELL'?amount-fees-tax:amount;await tx.portfolioCashBalance.upsert({where:{portfolioId_currency:{portfolioId,currency}},create:{id:randomUUID(),portfolioId,currency,balance:cashDelta},update:{balance:{increment:cashDelta}}});if(type==='BUY'&&assetType&&assetId&&quantity&&price!==null){await tx.portfolioTaxLot.create({data:{id:randomUUID(),portfolioId,transactionId:t.id,assetType:assetType as never,assetId,acquiredAt:t.occurredAt,originalQuantity:quantity,remainingQuantity:quantity,unitCost:(amount+fees+tax)/quantity,currency,fxRateToBase:num(b.fxRateToBase)}});const old=await tx.portfolioItem.findFirst({where:{portfolioId,assetType:assetType as never,assetId}});const oldQty=Number(old?.shares??0),oldBasis=Number(old?.costBasis??0),newBasis=oldBasis+amount+fees+tax;old?await tx.portfolioItem.update({where:{id:old.id},data:{shares:oldQty+quantity,costBasis:newBasis,avgCost:newBasis/(oldQty+quantity)}}):await tx.portfolioItem.create({data:{portfolioId,assetType:assetType as never,assetId,assetCode:text(b.assetCode,80)??assetId,assetName:text(b.assetName,200)??assetId,shares:quantity,costBasis:newBasis,avgCost:newBasis/quantity,currency}});}await tx.portfolioEvent.create({data:{id:randomUUID(),portfolioId,type:'TRANSACTION_ADDED',payload:{transactionId:t.id,transactionType:type,assetId}}});return t;});return ok(result,201);}catch(e){if(e instanceof Error&&e.message==='AUTH')return bad('Authentication required.',401);if(e instanceof Error&&e.message.includes('Unique constraint'))return bad('Duplicate transaction.',409);return bad('Unable to update portfolio.',500)}}

export async function PATCH(r:Request){try{const a=await owner(r),b=await body(r),id=text(b.portfolioId);if(!id||!await owned(id,a.id))return bad('Portfolio not found.',404);if(text(b.action,30)==='UPDATE_TRANSACTION'){const transactionId=text(b.transactionId),row=transactionId?await prisma.portfolioTransaction.findFirst({where:{id:transactionId,portfolioId:id}}):null;if(!row)return bad('Transaction not found.',404);const updated=await prisma.$transaction(async tx=>{const quantity=num(b.quantity)??Number(row.quantity),price=num(b.price)??Number(row.price),amount=num(b.amount)??(quantity*price);const saved=await tx.portfolioTransaction.update({where:{id:row.id},data:{quantity,price,amount,fees:num(b.fees)??Number(row.fees),tax:num(b.tax)??Number(row.tax),occurredAt:text(b.occurredAt)?new Date(text(b.occurredAt)!):row.occurredAt,note:b.note!==undefined?text(b.note,1000):row.note}});await rebuild(tx,id);await tx.portfolioEvent.create({data:{id:randomUUID(),portfolioId:id,type:'TRANSACTION_UPDATED',payload:{transactionId:row.id}}});return saved});return ok(updated);}return ok(await prisma.portfolio.update({where:{id},data:{...(text(b.name,80)?{name:text(b.name,80)!}:{}),...(b.description!==undefined?{description:text(b.description,500)}:{}),...(text(b.currency,3)?{currency:text(b.currency,3)!.toUpperCase()}:{}),...(b.benchmarkAssetId!==undefined?{benchmarkAssetId:text(b.benchmarkAssetId)}:{})}}));}catch(e){return bad(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to edit portfolio.',e instanceof Error&&e.message==='AUTH'?401:500)}}
export async function DELETE(r:Request){try{const a=await owner(r),b=await body(r),id=text(b.portfolioId);if(!id||!await owned(id,a.id))return bad('Portfolio not found.',404);const transactionId=text(b.transactionId);if(transactionId){await prisma.$transaction(async tx=>{const t=await tx.portfolioTransaction.findFirst({where:{id:transactionId,portfolioId:id}});if(!t)return;await tx.portfolioTaxLot.deleteMany({where:{transactionId:t.id}});await tx.portfolioTransaction.delete({where:{id:t.id}});await rebuild(tx,id);await tx.portfolioEvent.create({data:{id:randomUUID(),portfolioId:id,type:'TRANSACTION_REMOVED',payload:{transactionId}}});});return ok({deleted:true});}if(b.permanent===true)await prisma.portfolio.delete({where:{id}});else await prisma.portfolio.update({where:{id},data:{archivedAt:new Date(),isDefault:false}});return ok({deleted:true});}catch(e){return bad(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to delete portfolio data.',e instanceof Error&&e.message==='AUTH'?401:500)}}

