ALTER TABLE "fund_share_classes" ADD COLUMN "custodian_fee" DECIMAL(10,8), ADD COLUMN "switching_fee" DECIMAL(10,8), ADD COLUMN "regular_investment_available" BOOLEAN, ADD COLUMN "regular_investment_minimum" DECIMAL(24,4);

CREATE TABLE "fund_companies" ("id" TEXT PRIMARY KEY,"official_name" TEXT NOT NULL,"legal_name" TEXT,"country" TEXT,"domicile" TEXT,"website" TEXT,"regulator_id" TEXT,"source" TEXT NOT NULL,"source_record_id" TEXT,"verification_status" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "fund_companies_official_name_source_key" ON "fund_companies"("official_name","source");
CREATE TABLE "fund_company_mappings" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"source" TEXT NOT NULL,"source_record_id" TEXT,"verification_status" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "fund_company_mappings_identity_key" ON "fund_company_mappings"("fund_id","company_id","source"); CREATE INDEX "fund_company_mappings_company_id_idx" ON "fund_company_mappings"("company_id");
CREATE TABLE "fund_managers" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"source" TEXT NOT NULL,"source_record_id" TEXT,"verification_status" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_managers_name_source_key" ON "fund_managers"("name","source");
CREATE TABLE "fund_manager_assignments" ("id" TEXT PRIMARY KEY,"manager_id" TEXT NOT NULL,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"start_date" DATE,"end_date" DATE,"role" TEXT NOT NULL,"source" TEXT NOT NULL,"source_record_id" TEXT,"verified_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX "fund_manager_assignments_fund_id_start_date_idx" ON "fund_manager_assignments"("fund_id","start_date");
CREATE TABLE "fund_aum_observations" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"aum" DECIMAL(30,6) NOT NULL,"currency" TEXT NOT NULL,"observation_date" DATE NOT NULL,"grain" TEXT NOT NULL,"units_outstanding" DECIMAL(30,6),"source" TEXT NOT NULL,"source_record_id" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_aum_observations_identity_key" ON "fund_aum_observations"("fund_id","share_class_id","observation_date","source"); CREATE INDEX "fund_aum_observations_fund_id_observation_date_idx" ON "fund_aum_observations"("fund_id","observation_date");
CREATE TABLE "fund_distribution_observations" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"ex_date" DATE NOT NULL,"record_date" DATE,"pay_date" DATE,"distribution_amount" DECIMAL(24,10) NOT NULL,"distribution_currency" TEXT NOT NULL,"distribution_rate" DECIMAL(18,10),"distribution_type" TEXT,"income_component" DECIMAL(24,10),"capital_gain_component" DECIMAL(24,10),"return_of_capital" DECIMAL(24,10),"source" TEXT NOT NULL,"source_record_id" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_distribution_observations_identity_key" ON "fund_distribution_observations"("fund_id","share_class_id","ex_date","source","distribution_amount"); CREATE INDEX "fund_distribution_observations_fund_id_ex_date_idx" ON "fund_distribution_observations"("fund_id","ex_date");
CREATE TABLE "fund_annual_returns" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"calendar_year" INTEGER NOT NULL,"return_value" DECIMAL(24,10) NOT NULL,"return_semantics" TEXT NOT NULL,"start_date" DATE NOT NULL,"end_date" DATE NOT NULL,"source" TEXT NOT NULL,"calculation_method" TEXT NOT NULL,"as_of_date" DATE NOT NULL,"observation_count" INTEGER NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_annual_returns_identity_key" ON "fund_annual_returns"("fund_id","share_class_id","calendar_year","source","calculation_method"); CREATE INDEX "fund_annual_returns_fund_id_calendar_year_idx" ON "fund_annual_returns"("fund_id","calendar_year");
CREATE TABLE "fund_fee_history" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT NOT NULL,"calendar_year" INTEGER,"as_of_date" DATE NOT NULL,"management_fee" DECIMAL(10,8),"ongoing_charges" DECIMAL(10,8),"ter" DECIMAL(10,8),"custodian_fee" DECIMAL(10,8),"source" TEXT NOT NULL,"source_record_id" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_fee_history_identity_key" ON "fund_fee_history"("share_class_id","as_of_date","source"); CREATE INDEX "fund_fee_history_fund_id_calendar_year_idx" ON "fund_fee_history"("fund_id","calendar_year");
CREATE TABLE "fund_events" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"event_type" TEXT NOT NULL,"announcement_date" DATE,"effective_date" DATE NOT NULL,"source" TEXT NOT NULL,"source_record_id" TEXT,"verification_status" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_events_identity_key" ON "fund_events"("fund_id","share_class_id","event_type","effective_date","source","source_record_id"); CREATE INDEX "fund_events_fund_id_effective_date_idx" ON "fund_events"("fund_id","effective_date");
CREATE TABLE "fund_profile_provenance" ("id" TEXT PRIMARY KEY,"fund_id" TEXT NOT NULL,"share_class_id" TEXT,"field_name" TEXT NOT NULL,"source" TEXT NOT NULL,"source_record_id" TEXT,"as_of_date" DATE,"verification_status" TEXT NOT NULL,"grain" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "fund_profile_provenance_identity_key" ON "fund_profile_provenance"("fund_id","share_class_id","field_name","source","source_record_id"); CREATE INDEX "fund_profile_provenance_fund_id_field_name_idx" ON "fund_profile_provenance"("fund_id","field_name");
