-- Pending approval: do not deploy automatically.
CREATE TABLE IF NOT EXISTS ipo_offerings (
  id uuid PRIMARY KEY,
  canonical_ipo_id text NOT NULL UNIQUE,
  company_name text NOT NULL,
  legal_entity_name text,
  ticker text,
  expected_ticker text,
  exchange text,
  country text,
  sector text,
  industry text,
  listing_type text NOT NULL,
  filing_date date,
  expected_pricing_date date,
  actual_pricing_date date,
  expected_listing_date date,
  actual_listing_date date,
  date_certainty text,
  status text NOT NULL,
  offer_price numeric(28,10),
  price_range_low numeric(28,10),
  price_range_high numeric(28,10),
  shares_offered numeric(28,4),
  primary_shares numeric(28,4),
  secondary_shares numeric(28,4),
  greenshoe numeric(28,4),
  gross_proceeds numeric(28,2),
  net_proceeds numeric(28,2),
  implied_market_cap numeric(28,2),
  currency text,
  underwriters jsonb,
  lead_managers jsonb,
  bookrunners jsonb,
  cornerstone_investors jsonb,
  use_of_proceeds text,
  prospectus_url text,
  filing_url text,
  final_offering_document_url text,
  source text NOT NULL,
  source_event_key text NOT NULL,
  source_lineage jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_payload jsonb,
  revision integer NOT NULL DEFAULT 1,
  supersedes_id uuid REFERENCES ipo_offerings(id),
  stock_id text REFERENCES stocks(id),
  original_ticker text,
  isin text,
  cusip text,
  sedol text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(source, source_event_key, revision)
);
CREATE INDEX IF NOT EXISTS ipo_offerings_status_dates_idx ON ipo_offerings(status, COALESCE(actual_listing_date, expected_listing_date, actual_pricing_date, expected_pricing_date, filing_date));
CREATE INDEX IF NOT EXISTS ipo_offerings_stock_idx ON ipo_offerings(stock_id);

CREATE TABLE IF NOT EXISTS ipo_stock_mapping_queue (
  id uuid PRIMARY KEY,
  ipo_id uuid NOT NULL REFERENCES ipo_offerings(id),
  candidate_stock_id text REFERENCES stocks(id),
  status text NOT NULL DEFAULT 'PENDING',
  match_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  missing_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ipo_stock_mapping_queue_status_idx ON ipo_stock_mapping_queue(status, created_at);
