import { prisma } from '@/lib/prisma'; import { getAccountForRequest } from '@/lib/auth/userService';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const TYPES=['STOCK','ETF','FUND','INDEX','DERIVATIVES','FIXED_INCOME','FX','MACRO','COMMODITY','CRYPTO'] as const;
const FAMILIES=['PRICE_VALUE','TECHNICAL','FUNDAMENTAL','ETF_FUND','FIXED_INCOME','FX','MACRO','COMMODITY','CRYPTO','DERIVATIVES','FCN_SIMULATION'] as const;
const OPERATORS=['ABOVE','BELOW','CROSS_ABOVE','CROSS_BELOW','PERCENT_CHANGE','ABSOLUTE_CHANGE','EQUALS','GREATER_THAN_METRIC','LESS_THAN_METRIC'] as const;
const CAPABILITIES:Record<string,string[]>={STOCK:['PRICE','CHANGE','PERCENT_CHANGE'],ETF:['PRICE','NAV','CHANGE','PERCENT_CHANGE'],FUND:['NAV'],INDEX:['VALUE','CHANGE','PERCENT_CHANGE'],FIXED_INCOME:['YIELD'],FX:['RATE','CHANGE','PERCENT_CHANGE'],MACRO:['VALUE'],COMMODITY:['PRICE','CHANGE','PERCENT_CHANGE'],CRYPTO:['PRICE','CHANGE','PERCENT_CHANGE'],DERIVATIVES:['PRICE','VOLUME','OPENINTEREST','IV','DELTA','GAMMA','THETA','VEGA']};
const text=(v:unknown,n=100)=>typeof v==='string'&&v.trim()?v.trim().slice(0,n):null; const body=(r:Request)=>r.json().catch(()=>({})) as Promise<Record<string,unknown>>;
const ok=(data:unknown,status=200)=>Response.json({data,error:null},{status,headers:{'Cache-Control':'no-store'}}); const fail=(message:string,status=400)=>Response.json({data:null,error:{message}},{status});
async function account(request:Request){const value=await getAccountForRequest(request);if(!value)throw new Error('AUTH');return value}
async function ownedRule(id:string,userId:string){return prisma.watchlistAlertRule.findFirst({where:{id,ownerUserId:userId}})}
function parameters(value:unknown){
  const input=(value&&typeof value==='object'?value:{}) as Record<string,unknown>,logic=input.logic==='OR'?'OR':'AND',raw=Array.isArray(input.conditions)?input.conditions:[];
  const conditions=raw.slice(0,50).map((entry,index)=>{const c=(entry&&typeof entry==='object'?entry:{}) as Record<string,unknown>;return{id:text(c.id)??`c${index+1}`,assetId:text(c.assetId,200),assetType:text(c.assetType,30)?.toUpperCase(),metric:text(c.metric,80),operator:text(c.operator,40)?.toUpperCase(),threshold:typeof c.threshold==='number'&&Number.isFinite(c.threshold)?c.threshold:null,compareMetric:text(c.compareMetric,80)}});
  if(!conditions.length||conditions.some(c=>!c.assetId||!c.assetType||!TYPES.includes(c.assetType as never)||!c.metric||!c.operator||!OPERATORS.includes(c.operator as never))) throw new Error('CONDITIONS');
  return{schemaVersion:1,logic,conditions};
}
async function validateAssets(request:Request,p:{conditions:Array<{assetId:string|null;assetType:string|null|undefined}>}){for(const c of p.conditions){const url=new URL(`/api/mobile/assets/${encodeURIComponent(c.assetId!)}`,request.url);url.searchParams.set('type',c.assetType!);if(!(await fetch(url,{cache:'no-store'})).ok)return false}return true}
export async function GET(request:Request){try{const user=await account(request),url=new URL(request.url);if(url.searchParams.has('capabilities'))return ok({assetMetrics:CAPABILITIES,operators:OPERATORS,channels:['IN_APP','APP_PUSH','LINE','EMAIL'],cadences:['REALTIME_WHERE_AVAILABLE','INTRADAY','DAILY','PUBLICATION_EVENT','CUSTOM_SCHEDULE']});const history=url.searchParams.get('historyFor');if(history){if(!(await ownedRule(history,user.id)))return fail('Rule not found.',404);return ok(await prisma.watchlistAlertOccurrence.findMany({where:{ruleId:history},orderBy:{triggeredAt:'desc'},take:100}))}const rules=await prisma.watchlistAlertRule.findMany({where:{ownerUserId:user.id},orderBy:{createdAt:'desc'},take:100}),versions=await prisma.watchlistAlertRuleVersion.findMany({where:{id:{in:rules.map(rule=>rule.currentVersionId).filter((id):id is string=>Boolean(id))}}}),states=await prisma.watchlistAlertRuleState.findMany({where:{ruleId:{in:rules.map(rule=>rule.id)}}});return ok(rules.map(rule=>({...rule,parameters:versions.find(version=>version.id===rule.currentVersionId)?.parameters??null,state:states.find(state=>state.ruleId===rule.id)??null})))}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to load alerts.',e instanceof Error&&e.message==='AUTH'?401:500)}}
export async function POST(request:Request){try{const user=await account(request),input=await body(request),scope=text(input.scopeType,30)??'SINGLE_ASSET',watchlistId=text(input.watchlistId),family=text(input.ruleFamily,30)?.toUpperCase();if(!FAMILIES.includes(family as never))return fail('Unsupported rule family.');if(scope==='WATCHLIST'){if(!watchlistId||!(await prisma.watchlist.findFirst({where:{id:watchlistId,ownerUserId:user.id,archivedAt:null}})))return fail('Watchlist not found.',404)}const params=parameters(input.parameters);if(!(await validateAssets(request,params)))return fail('Canonical asset not found.',404);const first=params.conditions[0];const frequency=input.frequency==='ONE_TIME'?'ONE_TIME':'RECURRING',cadence=text(input.cadence,40)??'DAILY',channels=Array.isArray(input.deliveryChannels)?input.deliveryChannels.filter(x=>['APP_PUSH','IN_APP','LINE','EMAIL'].includes(String(x))).slice(0,4):['IN_APP'];const result=await prisma.$transaction(async tx=>{const rule=await tx.watchlistAlertRule.create({data:{ownerUserId:user.id,watchlistId,assetType:first.assetType!,canonicalAssetId:first.assetId,ruleFamily:family!,ruleKind:text(input.ruleKind,60)??'COMPOSITE',scopeType:scope,logicalOperator:params.logic,frequency,cadence,cooldownSeconds:Math.max(0,Math.min(2592000,Number(input.cooldownSeconds)||0)),deliveryChannels:channels,status:'ACTIVE'}});const version=await tx.watchlistAlertRuleVersion.create({data:{ruleId:rule.id,versionNumber:1,parameters:params,effectiveFrom:new Date(),createdBy:user.id}});await tx.watchlistAlertRule.update({where:{id:rule.id},data:{currentVersionId:version.id}});await tx.watchlistAlertRuleState.create({data:{ruleId:rule.id,ruleVersionId:version.id,evaluationVersion:'deterministic-v1',currentConditionState:'UNKNOWN',dataAvailability:'NOT_AVAILABLE'}});return{...rule,currentVersionId:version.id,parameters:params}});return ok(result,201)}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':e instanceof Error&&e.message==='CONDITIONS'?'Invalid conditions.':'Unable to create alert.',e instanceof Error&&e.message==='AUTH'?401:400)}}
export async function PATCH(request:Request){try{const user=await account(request),input=await body(request),id=text(input.id);if(!id||!(await ownedRule(id,user.id)))return fail('Rule not found.',404);const action=text(input.action,20);if(action==='PAUSE'||action==='RESUME'){return ok(await prisma.watchlistAlertRule.update({where:{id},data:{status:action==='PAUSE'?'PAUSED':'ACTIVE'}}))}const params=parameters(input.parameters),latest=await prisma.watchlistAlertRuleVersion.findFirst({where:{ruleId:id},orderBy:{versionNumber:'desc'}}),channels=Array.isArray(input.deliveryChannels)?input.deliveryChannels.filter(x=>['APP_PUSH','IN_APP','LINE','EMAIL'].includes(String(x))).slice(0,4):undefined;const version=await prisma.$transaction(async tx=>{await tx.watchlistAlertRuleVersion.updateMany({where:{ruleId:id,effectiveTo:null},data:{effectiveTo:new Date()}});const next=await tx.watchlistAlertRuleVersion.create({data:{ruleId:id,versionNumber:(latest?.versionNumber??0)+1,parameters:params,effectiveFrom:new Date(),createdBy:user.id}});await tx.watchlistAlertRule.update({where:{id},data:{currentVersionId:next.id,logicalOperator:params.logic,...(input.frequency==='ONE_TIME'||input.frequency==='RECURRING'?{frequency:input.frequency}:{}),...(text(input.cadence,40)?{cadence:text(input.cadence,40)!}:{}),...(Number.isFinite(Number(input.cooldownSeconds))?{cooldownSeconds:Math.max(0,Math.min(2592000,Number(input.cooldownSeconds)))}:{}),...(channels?{deliveryChannels:channels}:{})}});return next});return ok(version)}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to update alert.',e instanceof Error&&e.message==='AUTH'?401:400)}}
export async function DELETE(request:Request){try{const user=await account(request),input=await body(request),id=text(input.id);if(!id||!(await ownedRule(id,user.id)))return fail('Rule not found.',404);await prisma.watchlistAlertRule.delete({where:{id}});return ok({deleted:true})}catch(e){return fail(e instanceof Error&&e.message==='AUTH'?'Authentication required.':'Unable to delete alert.',e instanceof Error&&e.message==='AUTH'?401:500)}}
