CREATE TABLE IF NOT EXISTS futures_root_current_quotes (
  root_id UUID PRIMARY KEY REFERENCES futures_product_roots(id),
  yahoo_symbol TEXT NOT NULL UNIQUE,
  current_price NUMERIC(24,8),
  change NUMERIC(24,8),
  change_percent NUMERIC(24,8),
  open NUMERIC(24,8),
  high NUMERIC(24,8),
  low NUMERIC(24,8),
  previous_close NUMERIC(24,8),
  previous_settlement NUMERIC(24,8),
  bid NUMERIC(24,8),
  ask NUMERIC(24,8),
  current_volume BIGINT,
  open_interest BIGINT,
  market_time TIMESTAMPTZ,
  contract_month DATE,
  settlement_date DATE,
  expiry_date DATE,
  source TEXT NOT NULL DEFAULT 'YAHOO',
  source_url TEXT NOT NULL,
  field_status JSONB NOT NULL DEFAULT '{}'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
