import { prisma } from "../../prisma.ts";
import { WebDataError } from "./errors.ts";
import { freshnessStatus } from "./freshness.ts";
import { normalizePagination, paginationMeta } from "./pagination.ts";
import { buildProvenance } from "./provenance.ts";
import { getIndexReadinessMap } from "./publicReadiness.ts";
import { numberOrNull, type CanonicalIdentity, type HistoryQuery, type ListQuery, type SummaryMetrics } from "./types.ts";

const INDEX_QUERY_ALIASES:Record<string,string>={"日經225":"^N225","日經 225":"^N225","nikkei225":"^N225","標普500":"^GSPC","s&p500":"^GSPC","nasdaq":"^IXIC","道瓊":"^DJI","費城半導體":"^SOX","台灣加權":"^TWII","櫃買":"^TWOII","恆生":"^HSI","滬深300":"000300.SS","kospi":"^KS11"};
const INDEX_ZH:Record<string,string>={"^N225":"日經 225 指數","^GSPC":"標普 500 指數","^IXIC":"那斯達克綜合指數","^DJI":"道瓊工業平均指數","^SOX":"費城半導體指數","^RUT":"羅素 2000 指數","^VIX":"CBOE 波動率指數","^TWII":"台灣加權指數","^TWOII":"櫃買指數","^TOPX":"東證股價指數","^HSI":"恆生指數","^HSCE":"恆生中國企業指數","000001.SS":"上證綜合指數","000300.SS":"滬深 300 指數","399001.SZ":"深圳成分指數","^KS11":"韓國綜合股價指數","^STOXX":"STOXX 歐洲 600 指數","^GDAXI":"德國 DAX 指數","^FTSE":"英國富時 100 指數","^FCHI":"法國 CAC 40 指數"};
type Registry=Awaited<ReturnType<typeof prisma.globalIndexRegistry.findFirst>> & {};
type Candle={timestamp:Date;close:unknown;open:unknown;high:unknown;low:unknown;volume:unknown;source:string;ingestedAt:Date};
const resolveQuery=(value:string)=>INDEX_QUERY_ALIASES[value.normalize("NFKC").trim().toLowerCase()]??value.trim();
const identity=(row:NonNullable<Registry>):CanonicalIdentity=>({assetType:"INDEX",id:row.id,symbol:row.symbol,name:row.name,displayName:INDEX_ZH[row.symbol]??row.displayName??row.name,currency:row.currency,market:row.exchange??row.country,country:row.country??row.region});
const makeResponse=(row:NonNullable<Registry>,candles:Candle[],publicReady:boolean)=>{const latest=candles[0],previous=candles[1],close=numberOrNull(latest?.close),prior=numberOrNull(previous?.close),change=close!=null&&prior!=null?close-prior:null,changePercent=change!=null&&prior?change/prior*100:null;const metrics:SummaryMetrics={priceOrNav:close,change,changePercent,currency:row.currency,asOfDate:latest?.timestamp.toISOString()??null,performance1M:null,performance3M:null,performance1Y:null};const provenance=buildProvenance({source:latest?.source??row.provider,sourceRecordId:row.symbol,asOfDate:latest?.timestamp,lastUpdated:latest?.ingestedAt??row.updatedAt});return{data:{identity:identity(row),metrics,licensingStatus:row.licensingStatus,publicReady},meta:{asOfDate:provenance.asOfDate,lastUpdated:provenance.lastUpdated,freshnessStatus:freshnessStatus(latest?.timestamp,"MARKET_DAY"),source:provenance.source,provenance,coverageStatus:publicReady?"FULL" as const:"PARTIAL_CURRENT" as const}}};
async function latestByIds(ids:string[]){if(!ids.length)return new Map<string,Candle[]>();const rows=await prisma.$queryRawUnsafe<Array<Candle&{indexId:string}>>(`SELECT index_id AS "indexId",timestamp,close,open,high,low,volume,source,ingested_at AS "ingestedAt" FROM (SELECT c.*,row_number() OVER(PARTITION BY index_id ORDER BY timestamp DESC) rn FROM global_index_candles c WHERE interval='1d' AND index_id=ANY($1::text[])) ranked WHERE rn<=2 ORDER BY index_id,timestamp DESC`,ids);const map=new Map<string,Candle[]>();for(const row of rows){const list=map.get(row.indexId)??[];list.push(row);map.set(row.indexId,list)}return map;}
export async function getIndexList(query:ListQuery={}){const{page,pageSize,skip}=normalizePagination(query.page,query.pageSize);const term=query.query?.trim(),resolved=term?resolveQuery(term):null;const where={active:true,...(resolved?{OR:[{symbol:{contains:resolved,mode:"insensitive" as const}},{name:{contains:resolved,mode:"insensitive" as const}},{displayName:{contains:resolved,mode:"insensitive" as const}},{providerExternalId:{contains:resolved,mode:"insensitive" as const}}]}:{})};const[total,rows]=await prisma.$transaction([prisma.globalIndexRegistry.count({where}),prisma.globalIndexRegistry.findMany({where,skip,take:pageSize,orderBy:{symbol:"asc"}})]);const ids=rows.map(x=>x.id),[candles,ready]=await Promise.all([latestByIds(ids),getIndexReadinessMap(ids)]);const payload=rows.map(row=>makeResponse(row,candles.get(row.id)??[],ready.get(row.id)?.publicReady??false));const dates=payload.map(x=>x.meta.asOfDate).filter((x):x is string=>Boolean(x)).sort();return{data:payload.map(x=>x.data),meta:{asOfDate:dates.at(-1)??null,lastUpdated:new Date().toISOString(),freshnessStatus:"UNKNOWN" as const,source:"GLOBAL_INDEX_CANONICAL",provenance:buildProvenance({source:"GLOBAL_INDEX_CANONICAL",asOfDate:dates.at(-1)}),coverageStatus:"PARTIAL_CURRENT" as const},pagination:paginationMeta(page,pageSize,total),error:null};}
export const searchIndices=(query:string,options:Omit<ListQuery,"query">={})=>getIndexList({...options,query});
export async function getIndexSummaries(identifiers:readonly string[]){const keys=[...new Set(identifiers.map(resolveQuery))].slice(0,20);if(!keys.length)return[];const rows=await prisma.globalIndexRegistry.findMany({where:{active:true,OR:[{id:{in:keys}},{symbol:{in:keys}},{providerExternalId:{in:keys}}]},orderBy:{symbol:"asc"}});const ids=rows.map(x=>x.id),[candles,ready]=await Promise.all([latestByIds(ids),getIndexReadinessMap(ids)]);return rows.map(row=>makeResponse(row,candles.get(row.id)??[],ready.get(row.id)?.publicReady??false));}
async function findIndex(identifier:string){const key=decodeURIComponent(identifier).trim();if(!key)throw new WebDataError("INVALID_QUERY","An index identifier is required.");const resolved=resolveQuery(key);let row=await prisma.globalIndexRegistry.findFirst({where:{active:true,OR:[{id:resolved},{symbol:{equals:resolved,mode:"insensitive"}},{providerExternalId:{equals:resolved,mode:"insensitive"}},{name:{equals:resolved,mode:"insensitive"}},{displayName:{equals:resolved,mode:"insensitive"}}]}});if(!row){const alias=await prisma.globalIndexAlias.findFirst({where:{legacySymbol:{equals:resolved,mode:"insensitive"}}});if(alias)row=await prisma.globalIndexRegistry.findFirst({where:{id:alias.indexId,active:true}})}return row;}
export async function getIndexDetail(identifier:string){const row=await findIndex(identifier);if(!row)throw new WebDataError("NOT_FOUND","Index not found.");const [candles,ready]=await Promise.all([prisma.globalIndexCandle.findMany({where:{indexId:row.id,interval:"1d"},orderBy:{timestamp:"desc"},take:252}),getIndexReadinessMap([row.id])]);const state=ready.get(row.id);if(!state?.publicReady)throw new WebDataError("DATA_UNAVAILABLE","Index is not public ready.");return{...makeResponse(row,candles,state.publicReady),readiness:state,historySummary:{rows:state.historyRows,earliestDate:state.earliestDate,latestDate:state.latestDate},pagination:null,error:null};}
export async function getIndexHistory(identifier:string,query:HistoryQuery={}){const{page,pageSize,skip}=normalizePagination(query.page,query.pageSize);const row=await findIndex(identifier);if(!row)throw new WebDataError("NOT_FOUND","Index not found.");const ready=(await getIndexReadinessMap([row.id])).get(row.id);if(!ready?.publicReady)throw new WebDataError("DATA_UNAVAILABLE","Index is not public ready.");const cursor=query.cursor?new Date(query.cursor):null;const where={indexId:row.id,interval:"1d",timestamp:{...(query.from?{gte:query.from}:{}),...(query.to?{lte:query.to}:{}),...(cursor?{lt:cursor}:{})}};const[total,rows]=await prisma.$transaction([prisma.globalIndexCandle.count({where}),prisma.globalIndexCandle.findMany({where,skip:cursor?0:skip,take:pageSize,orderBy:{timestamp:"desc"}})]);const provenance=buildProvenance({source:rows[0]?.source??row.provider,sourceRecordId:row.symbol,asOfDate:rows[0]?.timestamp,lastUpdated:rows[0]?.ingestedAt});return{data:rows.map(x=>({timestamp:x.timestamp.toISOString(),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:numberOrNull(x.volume),source:x.source})),meta:{asOfDate:provenance.asOfDate,lastUpdated:provenance.lastUpdated,freshnessStatus:freshnessStatus(rows[0]?.timestamp,"MARKET_DAY"),source:provenance.source,provenance,coverageStatus:"FULL" as const},pagination:paginationMeta(page,pageSize,total,rows.length===pageSize?rows.at(-1)?.timestamp.toISOString()??null:null),error:null};}
export async function getIndexChart(identifier:string,from?:Date){const row=await findIndex(identifier);if(!row)throw new WebDataError("NOT_FOUND","Index not found.");const ready=(await getIndexReadinessMap([row.id])).get(row.id);if(!ready?.publicReady)throw new WebDataError("DATA_UNAVAILABLE","Index is not public ready.");const rows=await prisma.globalIndexCandle.findMany({where:{indexId:row.id,interval:"1d",...(from?{timestamp:{gte:from}}:{})},orderBy:{timestamp:"desc"},take:5000,select:{timestamp:true,close:true,high:true,low:true}});return rows.reverse().map(x=>({date:x.timestamp.toISOString(),close:Number(x.close),high:Number(x.high),low:Number(x.low)}));}
