CREATE TABLE IF NOT EXISTS "futures_positioning_analytics" (
  "observation_id" UUID NOT NULL,
  "market_id" UUID NOT NULL,
  "report_type" TEXT NOT NULL,
  "report_scope" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "as_of_date" DATE NOT NULL,
  "net_position" BIGINT NOT NULL,
  "long_pct_oi" DECIMAL(20,10),
  "short_pct_oi" DECIMAL(20,10),
  "spreading_pct_oi" DECIMAL(20,10),
  "net_pct_oi" DECIMAL(20,10),
  "net_change_1w" BIGINT,
  "net_change_4w" BIGINT,
  "net_change_13w" BIGINT,
  "net_change_26w" BIGINT,
  "net_change_52w" BIGINT,
  "percentile_1y" DECIMAL(10,8),
  "percentile_3y" DECIMAL(10,8),
  "percentile_5y" DECIMAL(10,8),
  "sample_count_1y" INTEGER NOT NULL DEFAULT 0,
  "sample_count_3y" INTEGER NOT NULL DEFAULT 0,
  "sample_count_5y" INTEGER NOT NULL DEFAULT 0,
  "formula_version" TEXT NOT NULL,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "futures_positioning_analytics_pkey" PRIMARY KEY ("observation_id"),
  CONSTRAINT "futures_positioning_analytics_observation_fkey" FOREIGN KEY ("observation_id") REFERENCES "futures_positioning_observations"("id") ON DELETE CASCADE,
  CONSTRAINT "futures_positioning_analytics_market_fkey" FOREIGN KEY ("market_id") REFERENCES "futures_positioning_markets"("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "futures_positioning_analytics_grain_idx" ON "futures_positioning_analytics"("market_id","report_type","report_scope","category","as_of_date");

CREATE TABLE IF NOT EXISTS "futures_positioning_coverage" (
  "market_id" UUID NOT NULL,
  "report_type" TEXT NOT NULL,
  "report_scope" TEXT NOT NULL,
  "identity_state" TEXT NOT NULL,
  "current_state" TEXT NOT NULL,
  "history_state" TEXT NOT NULL,
  "open_interest_state" TEXT NOT NULL,
  "net_position_state" TEXT NOT NULL,
  "change_state" TEXT NOT NULL,
  "percent_oi_state" TEXT NOT NULL,
  "percentile_state" TEXT NOT NULL,
  "provenance_state" TEXT NOT NULL,
  "freshness_state" TEXT NOT NULL,
  "detail_state" TEXT NOT NULL,
  "observation_dates" INTEGER NOT NULL,
  "earliest_date" DATE NOT NULL,
  "latest_date" DATE NOT NULL,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "futures_positioning_coverage_pkey" PRIMARY KEY ("market_id","report_type","report_scope"),
  CONSTRAINT "futures_positioning_coverage_market_fkey" FOREIGN KEY ("market_id") REFERENCES "futures_positioning_markets"("id") ON DELETE CASCADE
);
